# Generated by Django 6.0.5 on 2026-06-11 09:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='项目ID')),
                ('theme', models.CharField(help_text='如 family-revenge / overbearing-ceo', max_length=64, verbose_name='题材')),
                ('core_idea', models.TextField(help_text='一句话核心创意，用于生成剧本框架', verbose_name='核心创意')),
                ('episode_count', models.IntegerField(default=30, verbose_name='集数')),
                ('format_variant', models.CharField(choices=[('A', '变体 A'), ('B', '变体 B'), ('C', '变体 C'), ('D', '变体 D')], default='B', max_length=2, verbose_name='输出格式变体')),
                ('audience', models.CharField(blank=True, default='', max_length=200, verbose_name='目标受众')),
                ('reference_work', models.CharField(blank=True, default='', max_length=200, verbose_name='参考作品')),
                ('target_platform', models.CharField(blank=True, default='douyin', help_text='douyin / kuaishou / wechat / multi', max_length=32, verbose_name='目标平台')),
                ('episode_duration_minutes', models.FloatField(default=2.0, verbose_name='单集时长(分钟)')),
                ('creation_entry', models.CharField(blank=True, default='from-scratch', help_text='from-scratch / from-reference / from-trend', max_length=32, verbose_name='创作入口')),
                ('budget_level', models.CharField(blank=True, default='medium', help_text='low / medium / high', max_length=16, verbose_name='预算档位')),
                ('global_market', models.CharField(blank=True, default='domestic', max_length=16, verbose_name='市场范围')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '创作中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('current_node_index', models.IntegerField(default=0, help_text='0 表示未开始，1-7 表示正在/已完成该节点', verbose_name='当前节点索引')),
                ('total_nodes', models.IntegerField(default=7, verbose_name='总节点数')),
                ('progress_percent', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('error_message', models.TextField(blank=True, default='', help_text='status=failed 时填充', verbose_name='错误信息')),
                ('fusion_status', models.CharField(blank=True, choices=[('draft', '立项中'), ('planning', '策划中'), ('writing', '创作中'), ('reviewing', '质检中'), ('scoring', '评分中'), ('ready', '可发布'), ('blocked', '需修改')], default='', max_length=16, verbose_name='融合流程状态')),
                ('overall_score', models.FloatField(blank=True, null=True, verbose_name='8维综合分')),
                ('grade', models.CharField(blank=True, default='', max_length=16, verbose_name='报告等级')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='可发布时间')),
                ('skill_version', models.CharField(blank=True, default='', help_text='来自 demo4book project-config projectMeta.version', max_length=32, verbose_name='技能版本')),
                ('compliance_tier', models.CharField(blank=True, default='domestic', help_text='domestic | ai-comic | global-*', max_length=32, verbose_name='合规分层')),
                ('title', models.CharField(blank=True, default='', help_text='仅后台展示与作品列表使用', max_length=200, verbose_name='剧本标题')),
                ('total_duration_minutes', models.IntegerField(default=0, verbose_name='预计总时长(分钟)')),
                ('rendered_progress_html', models.TextField(blank=True, default='', help_text='由 services 层生成，前端直接插入 DOM', verbose_name='预渲染进度 HTML')),
                ('rendered_result_html', models.TextField(blank=True, default='', help_text='完成时生成，含数字水印，前端直接展示', verbose_name='预渲染结果 HTML')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(help_text='该创作归属的会员用户', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('user_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='membership.usermembership', verbose_name='消耗的会员')),
            ],
            options={
                'verbose_name': '创作项目',
                'verbose_name_plural': '创作项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('file_format', models.CharField(default='md', max_length=8)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='creation.project')),
            ],
            options={
                'verbose_name': '下载 token',
                'verbose_name_plural': '下载 token',
            },
        ),
        migrations.CreateModel(
            name='CreationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='节点ID')),
                ('node_index', models.IntegerField(help_text='1-7', verbose_name='节点编号')),
                ('fusion_node_id', models.CharField(blank=True, default='', help_text='如 node-6-review / node-8-score，来自 project-config', max_length=64, verbose_name='融合节点ID')),
                ('node_name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('node_description', models.CharField(blank=True, default='', max_length=300, verbose_name='节点描述')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('summary_text', models.TextField(blank=True, default='', help_text='节点完成后的简短可读描述，用于生成 progress HTML', verbose_name='节点摘要文本')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='耗时(秒)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='creation.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '创作节点',
                'verbose_name_plural': '创作节点',
                'ordering': ['project_id', 'node_index'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFusionArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_key', models.CharField(help_text='project_brief / gate_full / script_score_report 等', max_length=64, verbose_name='产物键')),
                ('payload', models.JSONField(default=dict, verbose_name='JSON 载荷')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fusion_artifacts', to='creation.project')),
            ],
            options={
                'verbose_name': '融合产物',
                'verbose_name_plural': '融合产物',
            },
        ),
        migrations.CreateModel(
            name='ScriptWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='作品文件ID')),
                ('file_format', models.CharField(choices=[('md', 'Markdown'), ('html', 'HTML'), ('zip', 'ZIP 打包'), ('pdf', 'PDF')], default='md', max_length=8, verbose_name='文件格式')),
                ('storage_path', models.CharField(help_text='不直接暴露给前端，由服务层鉴权后访问', max_length=500, verbose_name='加密存储路径')),
                ('file_name', models.CharField(help_text='下载时展示给用户', max_length=255, verbose_name='原始文件名')),
                ('size_bytes', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('watermark_token', models.CharField(help_text='含 user_id + project_id + timestamp 信息，用于溯源', max_length=64, unique=True, verbose_name='数字水印 token')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='creation.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '剧本作品文件',
                'verbose_name_plural': '剧本作品文件',
                'ordering': ['project_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='分享ID')),
                ('token', models.CharField(help_text='一次性随机字符串，公开可访问', max_length=64, unique=True, verbose_name='分享 token')),
                ('view_limit', models.IntegerField(default=100, verbose_name='最大查看次数')),
                ('view_count', models.IntegerField(default=0, verbose_name='已查看次数')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('allow_download', models.BooleanField(default=False, verbose_name='允许下载')),
                ('custom_title', models.CharField(blank=True, default='', max_length=200, verbose_name='自定义标题')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后查看时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='creation.project', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '分享链接',
                'verbose_name_plural': '分享链接',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='creation_pr_user_id_842fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='creation_pr_status_6bf3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['token'], name='creation_do_token_2ab92a_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['expires_at'], name='creation_do_expires_354683_idx'),
        ),
        migrations.AddIndex(
            model_name='creationnode',
            index=models.Index(fields=['project_id', 'node_index'], name='creation_cr_project_0a3831_idx'),
        ),
        migrations.AddIndex(
            model_name='creationnode',
            index=models.Index(fields=['status'], name='creation_cr_status_ef3031_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creationnode',
            unique_together={('project', 'node_index')},
        ),
        migrations.AddIndex(
            model_name='projectfusionartifact',
            index=models.Index(fields=['project', 'artifact_key'], name='creation_pr_project_78f3f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfusionartifact',
            unique_together={('project', 'artifact_key')},
        ),
        migrations.AddIndex(
            model_name='scriptwork',
            index=models.Index(fields=['project_id'], name='creation_sc_project_6f68df_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptwork',
            index=models.Index(fields=['watermark_token'], name='creation_sc_waterma_3c82a0_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['token'], name='creation_sh_token_43e744_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['user', '-created_at'], name='creation_sh_user_id_af5bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['expires_at'], name='creation_sh_expires_3f9bbd_idx'),
        ),
    ]
