# Generated by Django 6.0.5 on 2026-06-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0004_agent_execution_trace'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentexecutionrun',
            new_name='creation_ag_project_659c9a_idx',
            old_name='creation_ag_project_8d0f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentexecutionrun',
            new_name='creation_ag_agent_i_1389a7_idx',
            old_name='creation_ag_agent_i_6b8a11_idx',
        ),
        migrations.RenameIndex(
            model_name='subskillexecutionlog',
            new_name='creation_su_run_id_a5099d_idx',
            old_name='creation_su_run_id_0f6d84_idx',
        ),
        migrations.RenameIndex(
            model_name='subskillexecutionlog',
            new_name='creation_su_skill_i_6e6aab_idx',
            old_name='creation_su_skill_i_2c0b9a_idx',
        ),
    ]
