# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0005_rename_creation_ag_project_8d0f2d_idx_creation_ag_project_659c9a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_entry',
            field=models.CharField(blank=True, default='from-scratch', help_text='from-scratch / from-outline / from-reference / ip-sequel / novel-adaptation', max_length=32, verbose_name='创作入口'),
        ),
    ]
