# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0006_alter_project_creation_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reference_work',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='参考作品'),
        ),
    ]
