# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-15 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0007_alter_project_reference_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptQualityDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField(blank=True, help_text='具体集数；null 表示整体性问题', null=True, verbose_name='集数')),
                ('dimension', models.CharField(db_index=True, help_text='hook/emotion/reversal/structure/compliance', max_length=50, verbose_name='质量维度')),
                ('defect_type', models.CharField(help_text='如 hook_too_weak / qdn_mismatch / paywall_missing', max_length=100, verbose_name='缺陷类型')),
                ('score', models.FloatField(blank=True, help_text='该维度得分（0-100），null 表示未评分', null=True, verbose_name='得分')),
                ('details', models.JSONField(blank=True, default=dict, help_text="自由结构，如 { threshold: 75, actual: 62, suggestion: '...' }", verbose_name='详细信息')),
                ('source', models.CharField(choices=[('auto', '自动检测'), ('manual', '人工标注')], db_index=True, default='auto', max_length=20, verbose_name='来源')),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved', '已处理')], db_index=True, default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_defects', to='creation.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '剧本质量缺陷',
                'verbose_name_plural': '剧本质量缺陷',
                'db_table': 'creation_script_quality_defect',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='sqd_project_status_idx'), models.Index(fields=['dimension', 'defect_type'], name='sqd_dimension_idx')],
            },
        ),
    ]
