# Generated by Django 6.0.5 on 2026-06-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0008_scriptqualitydefect'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationnode',
            name='convergence_state',
            field=models.CharField(choices=[('pending', '初始'), ('converge', '收敛中'), ('stagnate', '停滞'), ('diverge', '发散'), ('oscillate', '振荡'), ('blocked', '已停机')], default='pending', max_length=16, verbose_name='收敛状态'),
        ),
        migrations.AddField(
            model_name='creationnode',
            name='fix_blocked_reason',
            field=models.CharField(blank=True, default='', help_text='convergence_state=blocked 时填充，供 Agent/前端展示', max_length=500, verbose_name='停机原因'),
        ),
        migrations.AddField(
            model_name='creationnode',
            name='fix_round',
            field=models.IntegerField(default=0, help_text='当前已执行的修复轮数，每次 fix-episode 完成后 +1', verbose_name='修复轮次'),
        ),
        migrations.AddField(
            model_name='creationnode',
            name='max_fix_rounds',
            field=models.IntegerField(default=5, help_text='硬上限，由 skill-thresholds.json#maxFixRounds 按节点类型覆盖', verbose_name='最大修复轮次'),
        ),
        migrations.AddField(
            model_name='creationnode',
            name='score_history',
            field=models.JSONField(blank=True, default=list, help_text='每轮修复后的 total_score 列表 [s1, s2, ...]，由 ConvergenceService 追加', verbose_name='分数历史'),
        ),
        migrations.AddIndex(
            model_name='creationnode',
            index=models.Index(fields=['convergence_state'], name='creation_cr_converg_56b06b_idx'),
        ),
    ]
