# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0009_convergence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='character_continuity_state',
            field=models.JSONField(blank=True, default=dict, help_text='由 drama-continuity-recorder 维护的人设/事件连续性档案。结构见 drama-continuity-recorder/SKILL.md#character-states.json。前端工作台用于展示跨集一致性概览，不直接用于创作逻辑。', verbose_name='连续性档案'),
        ),
    ]
