# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0010_character_continuity_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationnode',
            name='node_role',
            field=models.CharField(blank=True, choices=[('create', '内容生成'), ('review', '质量审核'), ('fix', '内容修复'), ('score', '剧本评分'), ('deliver', '交付导出'), ('', '未设定')], db_index=True, default='', help_text='review/score 节点必须通过 get_reviewable_artifact() 接口读取产物，禁止直接读取同项目 create 节点的实时中间产物，避免自评偏差。', max_length=16, verbose_name='节点角色'),
        ),
    ]
