# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0011_node_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationnode',
            name='last_failed_dimensions',
            field=models.JSONField(blank=True, default=list, help_text="上一轮 review 中未通过的维度 key 列表（G-Eval 模式）。下轮 review 时只复查这些维度，防止维度漂移。示例：['pacing', 'plot_structure', 'compliance']", verbose_name='上轮失败维度'),
        ),
    ]
