# Generated by Django 6.0.5 on 2026-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0019_independent_agent_run_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='batchjob',
            name='creation_batch_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchjob',
            name='creation_batch_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchproject',
            name='creation_batchproj_job_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchproject',
            name='creation_batchproj_row_idx',
        ),
        migrations.AlterUniqueTogether(
            name='creationnode',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='creationnode',
            name='creation_cr_project_0a3831_idx',
        ),
        migrations.RemoveIndex(
            model_name='creationnode',
            name='creation_cr_status_ef3031_idx',
        ),
        migrations.RemoveIndex(
            model_name='creationnode',
            name='creation_cr_converg_56b06b_idx',
        ),
        migrations.RemoveIndex(
            model_name='creationtask',
            name='task_project_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='creationtask',
            name='task_state_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='subskillexecutionlog',
            name='creation_su_run_id_a5099d_idx',
        ),
        migrations.RemoveIndex(
            model_name='subskillexecutionlog',
            name='creation_su_skill_i_6e6aab_idx',
        ),
        migrations.RemoveConstraint(
            model_name='subskillexecutionlog',
            name='uniq_sub_skill_per_run',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='creation_pr_abandon_5e545d_idx',
            old_name='proj_abandon_status_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='creation_pr_created_c5357f_idx',
            old_name='proj_created_status_idx',
        ),
        migrations.RenameIndex(
            model_name='referencematerial',
            new_name='creation_re_user_id_313e95_idx',
            old_name='creation_refmat_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='referencematerial',
            new_name='creation_re_parse_s_b3c7c1_idx',
            old_name='creation_refmat_parse_status_idx',
        ),
        migrations.RenameIndex(
            model_name='referencematerialinjection',
            new_name='creation_re_project_585254_idx',
            old_name='creation_refmat_inj_project_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='skill_version',
            field=models.CharField(blank=True, default='', help_text='来自历史 project-config projectMeta.version', max_length=32, verbose_name='技能版本'),
        ),
        migrations.AlterField(
            model_name='referencematerial',
            name='parsed_content',
            field=models.JSONField(blank=True, default=dict, help_text='解析后的结构化内容，结构：{"world":{"setting":"...","rules":["...",...]},"characters":[{"name":"...","role":"...","description":"..."}],"plot_structure":{"acts":[...],"twists":[...]},"themes":["...",...]}', verbose_name='解析内容'),
        ),
        migrations.AlterField(
            model_name='referencematerialinjection',
            name='injected_fields',
            field=models.JSONField(blank=True, default=list, help_text="已注入的字段列表，如 ['world', 'characters']", verbose_name='注入字段'),
        ),
        migrations.RemoveField(
            model_name='batchproject',
            name='batch_job',
        ),
        migrations.RemoveField(
            model_name='batchproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='creationnode',
            name='project',
        ),
        migrations.RemoveField(
            model_name='creationtask',
            name='project',
        ),
        migrations.RemoveField(
            model_name='creationtask',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='subskillexecutionlog',
            name='run',
        ),
        migrations.DeleteModel(
            name='BatchJob',
        ),
        migrations.DeleteModel(
            name='BatchProject',
        ),
        migrations.DeleteModel(
            name='CreationNode',
        ),
        migrations.DeleteModel(
            name='CreationTask',
        ),
        migrations.DeleteModel(
            name='SubSkillExecutionLog',
        ),
    ]
