# Generated by Django 6.0.5 on 2026-06-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0021_agent_run_concurrency_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentexecutionrun',
            new_name='creation_ag_project_94d772_idx',
            old_name='creation_ag_project_status_idx',
        ),
        migrations.AlterField(
            model_name='scriptqualitydefect',
            name='dimension',
            field=models.CharField(choices=[('hook', '钩子/开场'), ('emotion', '情绪设计'), ('reversal', '反转'), ('structure', '结构节奏'), ('compliance', '合规')], db_index=True, help_text='hook/emotion/reversal/structure/compliance', max_length=50, verbose_name='质量维度'),
        ),
    ]
