# Generated by Cursor Agent on 2026-06-26
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creation", "0030_expand_project_theme_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="quality_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{'overall': 82, 'format': 88, 'structure': 85, ...}",
                verbose_name="Drama 10维评分",
            ),
        ),
    ]
