# -*- coding: utf-8 -*-
"""Drama 产物与字段中文标签。"""
from __future__ import annotations

from typing import Dict

from apps.drama.defaults import DRAMA_ROLE_DEFAULTS

ARTIFACT_LABELS: Dict[str, str] = {}
SCHEMA_LABELS: Dict[str, str] = {}

for role in DRAMA_ROLE_DEFAULTS:
    key = role.get("default_output_artifact_key")
    contract = role.get("output_contract") or {}
    schema = str(contract.get("schema_version") or "")
    if key:
        ARTIFACT_LABELS.setdefault(key, role.get("name_zh") or key)
    if schema:
        SCHEMA_LABELS.setdefault(schema, role.get("name_zh") or schema)

# 补充非默认产物键
ARTIFACT_LABELS.update(
    {
        "project_brief": "立项简报",
        "episode_scripts": "分集剧本",
        "series_outline": "系列大纲",
        "character_bible": "人物小传",
        "review_report": "审稿报告",
        "quality_report": "质量报告",
        "compliance_report": "合规报告",
        "marketing_kit": "营销物料",
        "market_report": "市场分析报告",
        "narrative_plan": "叙事工程方案",
        "adaptation_plan": "IP改编方案",
        "conflict_plan": "冲突规划",
        "delivery_pack": "交付包",
        "dream_check": "梦想指数校验",
        "emotion_audit": "情绪审计",
        "emotion_blueprint": "情绪蓝图",
        "emotion_curve": "情绪曲线",
        "evolution_proposal": "演进提案",
        "formula_analysis": "爆款公式分析",
        "hook_plan": "钩子规划",
        "lapian_report": "拉片报告",
        "market_analysis": "市场分析",
        "post_assets": "后期资产",
        "project_review": "立项复审",
        "psychology_guide": "心理学指南",
        "reader_review": "读者评审",
        "reversal_plan": "反转规划",
        "storyboard": "分镜表",
        "style_check": "风格校验",
        "visual_pack": "视觉包",
        "visual_prompts": "视觉提示词",
        "word_count_report": "字数报告",
    }
)

FIELD_LABELS: Dict[str, str] = {
    "core_idea": "核心创意",
    "target_audience": "目标受众",
    "genre_positioning": "题材定位",
    "dream_index_forecast": "爆款预估",
    "differentiated_selling_points": "差异化卖点",
    "topic_suggestion": "选题建议",
    "theme_heat_rating": "题材热度",
    "platform_traffic_preference": "平台流量偏好",
    "competitive_product_analysis": "竞品分析",
    "爆款特征_matching_degree": "爆款特征匹配度",
    "hit_feature_matching_degree": "爆款特征匹配度",
    "optimization_direction": "优化方向",
    "estimated_market_performance": "预期市场表现",
    "trend_tag": "趋势标签",
    "core_hot_labels": "核心热词",
    "market_saturation": "市场饱和度",
    "user_demand_growth_rate": "用户需求增长率",
    "current_popularity_score": "当前热度评分",
    "target_platform": "目标平台",
    "audience_portrait": "受众画像",
    "traffic_weight_tags": "流量权重标签",
    "explicit_platform_benefit": "平台激励政策",
    "competitor_name": "竞品名称",
    "defect": "缺陷分析",
    "core_score": "核心评分",
    "episode_count": "集数",
    "working_title": "工作标题",
    "title": "标题",
    "summary": "摘要",
    "verdict": "结论",
    "final_verdict": "最终结论",
    "overall_result": "总体结果",
    "rating": "评级",
    "total_score": "总分",
    "name": "姓名",
    "identity": "身份",
    "surface_want": "表层欲望",
    "surface_desire": "表层欲望",
    "deep_need": "深层需求",
    "want": "欲望",
    "need": "需求",
    "flaw": "缺陷",
    "character_flaw": "缺陷",
    "ghost": "心魔",
    "core_fear": "核心恐惧",
    "lie": "错误信念",
    "timbre_tag": "音色标签",
    "timbre_ta": "音色标签",
    "voice_tag": "音色标签",
    "tone": "语调",
    "speed": "语速",
    "emotion_base": "基底情绪",
    "ending_hook": "集末钩子",
    "sceneHeader": "场景头",
    "action": "动作",
    "dialogue": "台词",
    "description": "说明",
    "type": "类型",
    "passed": "是否通过",
    "pacingPassed": "节奏通过",
    "issueType": "问题类型",
    "sceneNumber": "场次",
    "episodeNumber": "集号",
    "memoryCheckPoint": "记忆检查点",
    "relationship_network": "关系网络",
    "main_characters": "主要角色",
    "characters": "角色列表",
    "core_supporting_characters": "核心配角",
    "episode_outlines": "分集大纲",
    "episode_breakdown": "分集拆解",
    "rhythm_control": "节奏控制",
    "rhythm_dual_track_validation": "双轨节奏校验",
    "plot_rhythm_check": "情节节奏校验",
    "emotion_rhythm_check": "情绪节奏校验",
    "interaction_design_verification": "互动设计校验",
    "four_segment_structure": "四段结构",
    "emotion_markers": "情绪标记",
    "end_hook": "集末钩子",
    "core_task": "阶段任务",
    # ── 叙事工程 narrative-plan.v1 ──
    "narrative_core_objective": "叙事核心目标",
    "target_episode_range": "目标集数范围",
    "narrative_mechanics": "叙事机制",
    "mechanism_type": "机制类型",
    "implementation_details": "落地细节",
    "episode_narrative_designs": "分集叙事设计",
    "narrative_focus": "叙事焦点",
    "narrative_beat_timing": "节拍时间轴",
    "audience_emotion_design": "观众情绪设计",
    "key_narrative_techniques": "关键叙事技法",
    "worldview_delivery_points": "世界观传递点",
    "narrative_consistency_check": "叙事一致性校验",
    "six_stage_narrative": "六段叙事",
    "plot_beat": "情节节拍",
    "emotion_beat": "情绪节拍",
    "core_rules": "核心规则",
    "core_spaces": "核心场景",
    "core_space": "核心场景",
    "space_name": "场景名称",
    "repair_suggestions": "修复建议",
    "insert_event": "插入事件",
    "target_episode": "目标集数",
    "insert_position": "插入位置",
    "three_unique_selling_points": "三大差异化卖点",
    "three_differentiated_selling_points": "三大差异化卖点",
    "review_conclusion": "复审结论",
    "review_notes": "复审说明",
    "market_feasibility_score": "市场可行性得分",
    "creation_feasibility_score": "创作可行性得分",
    "compliance_risk_score": "合规风险得分",
    "final_rating": "最终评级",
    "core_evaluation": "核心评估",
    "final_explosive_score": "爆款指数",
    "explosive_level": "爆款等级",
    "sense_of_security": "安全感",
    "sense_of_satisfaction": "满足感",
    "sense_of_reality": "真实感",
    "estimated_total_play": "预估总播放",
    "estimated_revenue_input_ratio": "投入产出比",
    "hook_content": "钩子内容",
    "card_position": "卡点位置",
    "episode_id": "集号",
    "episode_name": "集名",
    "end_hook": "集末钩子",
    "four_segment_structure": "四段结构",
    "opening": "开场",
    "development": "发展",
    "climax": "高潮",
    "closing": "收尾",
    "resolution": "收束",
    "core_goal": "阶段目标",
    "stage_name": "阶段名称",
    "episode_range": "集数范围",
    "key_plot_points": "关键情节点",
    "crisis_depth_check": "危机深度校验",
    "a_level_reverse_points": "A级反转点",
    "reverse_content": "反转内容",
    "emotion_beat": "情绪节拍",
    "total_episodes": "总集数",
    "p0_check_result": "P0 检查结果",
    "p1_check_result": "P1 检查结果",
    "p2_check_result": "P2 检查结果",
    "overall_conclusion": "合规结论",
    "p0_risk": "P0 风险",
    "p1_risk": "P1 风险",
    "p2_risk": "P2 风险",
    "nine_dimension_risk": "九维风险",
    "p1_check_result": "P1 检查结果",
    "p2_check_result": "P2 检查结果",
    "nine_dimension_risk_check": "九维风险扫描",
    "source_id": "源角色",
    "target_id": "目标角色",
    "relationship_type": "关系类型",
    "interaction_rule": "互动规则",
    "role_position": "角色定位",
    "role_type": "角色类型",
    "character_arc": "人物弧光",
    "arc": "人物弧光",
    "quality_score": "质量分",
    "delivery_file_list": "交付文件清单",
    "evaluation_summary": "评估摘要",
    "global_overview": "全局概览",
    "storyboard_list": "分镜列表",
    "scriptContent": "剧本正文",
    "memoryCheckpoint": "记忆检查点",
    "first_episode_retention_forecast": "首集留存预估",
    "payment_conversion_forecast": "付费转化预估",
    "abandon_risk_points": "弃剧风险点",
    "emotion_performance": "情绪表现",
    "repair_suggestions": "修复建议",
    "final_verification": "最终校验",
    "drama_type": "剧种类型",
    "platform_diff_strategy": "平台差异化策略",
    "synopses": "剧情简介",
    "payment_copy": "付费文案",
    "streaming_titles": "流媒体标题",
    # ── 心理引导 / 预期管理（用户截图中的英文字段）──
    "type_expectation": "类型预期",
    "character_expectation": "角色预期",
    "foreshadowing_expectation": "伏笔预期",
    "established_expectation": "既定预期",
    "subversion_design": "颠覆设计",
    "immersion_design": "沉浸设计",
    "cognitive_gap_design": "认知差设计",
    "expectation_management": "预期管理",
    "emotion_resonance_trigger": "情绪共鸣触发",
    "obstacle_realism": "障碍真实感",
    "reaction_rationality": "反应合理性",
    "universal_character_goal": "共性角色目标",
    "known_info": "已知信息",
    "unknown_info": "未知信息",
    "information_difference_trigger": "信息差触发",
    "trigger_design": "触发设计",
    "resonance_point": "共鸣点",
    # ── 质量评分维度 ──
    "hook_effect": "钩子效果",
    "emotion_curve": "情绪曲线",
    "dream_indicator": "梦境指标",
    "dialogue_quality": "对白质量",
    "character_shaping": "人物塑造",
    "format_specification": "格式规范",
    "commercial_feasibility": "商业可行性",
    "structural_completeness": "结构完整性",
    "format_issues": "格式规范",
    "structure_issues": "结构完整性",
    "character_performance": "人物塑造",
    "dream_safety_index": "梦境指标",
    "commercial_potential": "商业可行性",
    # ── 拉片 / 节奏 / 世界 ──
    "camera_language": "镜头语言",
    "dialogue_design": "台词设计",
    "reusable_template": "可复用模板",
    "new_mode": "新模式",
    "character_analysis": "人设分析",
    "structure_analysis": "结构拆解",
    "emotion_beat_distribution": "情绪节拍分布",
    "no_drag_segment": "无拖沓段落",
    "avg_hook_interval": "平均钩子间隔",
    "contrast_shot": "对比镜头",
    "opening_close_up": "开场特写",
    "final_romance_shot": "结局浪漫镜头",
    "era_background": "时代背景",
    "power_structure": "权力结构",
    "top_tier": "顶层势力",
    "second_tier": "中层势力",
    "third_tier": "基层势力",
    "vision_constraints": "愿景约束",
    "taboo_constraints": "禁忌约束",
    "special_rules": "特殊规则",
    "core_world_rules": "世界核心规则",
    "top_tier": "顶层势力",
    "second_tier": "第二层势力",
    "third_tier": "第三层势力",
    # ── 大纲 / 情绪曲线校验 ──
    "a_level_reversal_check": "A级反转校验",
    "a_level_reverse_count": "A级反转次数",
    "emotion_platform_check": "情绪平台校验",
    "double_track_rhythm_note": "双轨节奏说明",
    "rhythm_control_verification": "节奏校验",
    "six_phase_narrative_structure": "六段叙事结构",
    "establish_world": "建立世界",
    "conflict_intro": "冲突引入",
    "escalate_opposition": "升级对抗",
    "crisis_explosion": "危机爆发",
    "eve_of_final": "决战前夕",
    "final_showdown": "最终对决",
    "four_part_structure": "四段结构",
    "emotion_markers": "情绪标记",
    "compliance_check": "合规校验",
    "hook_density_check": "钩子密度校验",
    "crisis_period_et_check": "危机期低谷校验",
    "final_episode_peak_check": "末集峰值校验",
    "total_episodes": "总集数",
    "et_min_value": "ET 最低值",
    "no_consecutive_3_flat": "无连续三集平盘",
    # ── 梦境指标 / 爆款公式 ──
    "absolute_safety": "绝对安全",
    "enhanced_realism": "增强真实感",
    "efficient_satisfaction": "高效满足",
    "evaluation_note": "评估说明",
    "detail_feedback": "详细反馈",
    "market_demand": "市场需求",
    "rhythm_matching": "节奏匹配",
    "competitive_barrier": "竞争壁垒",
    "platform_policy_fit": "平台政策契合",
    # ── 冲突 / 反转 ──
    "overall_conflict_gradient": "整体冲突梯度",
    "total_conflict_count": "冲突总数",
    "truth_reversals": "真相反转",
    "identity_reversals": "身份反转",
    "situation_reversals": "处境反转",
    "motivation_reversals": "动机反转",
    "relationship_reversals": "关系反转",
    "scene_name": "场景名称",
    "conflict_type": "冲突类型",
    "conflict_upgrade_path": "冲突升级路径",
    "reversal_name": "反转名称",
    "reverse_design": "反转设计",
    # ── 风格校验 ──
    "emotional_tone_check": "情绪基调校验",
    "narrative_style_check": "叙事风格校验",
    "personality_language_check": "人物语言校验",
    "check_status": "检查状态",
    # ── 字数 / 交付 / 营销 ──
    "total_cjk_chars": "总汉字数",
    "total_dialogue_cjk_chars": "台词汉字总数",
    "global_dialogue_ratio": "全局台词占比",
    "all_episodes_compliant": "全集合规",
    "dialogue_ratio": "台词占比",
    "adjust_suggestion": "调整建议",
    "bitter_sugar_ratio": "苦甜比",
    "short_shot_ratio": "短镜头占比",
    "per_episode_hook_count": "单集钩子数",
    "titles": "候选标题",
    "status": "状态",
    "compliance_check": "合规检查",
    # ── 角色 / 钩子 / 其他常用 ──
    "female_protagonist": "女主",
    "male_protagonist": "男主",
    "protagonist": "主角",
    "main_protagonist": "主角",
    "antagonist": "反派",
    "main_antagonist": "核心反派",
    "secondary_antagonist": "次要反派",
    "tertiary_antagonist": "帮凶",
    "supporting": "配角",
    "supporting_character": "配角",
    "core_supporting": "核心配角",
    "love_interest": "情感对象",
    "mentor": "导师",
    "cameo": "客串",
    # ── 关系 / 角色英文短语 ──
    "former daughter-in-law": "前儿媳",
    "former daughter in law": "前儿媳",
    "arch-enemy": "死敌",
    "arch enemy": "死敌",
    "ex-husband": "前夫",
    "ex husband": "前夫",
    "ex-wife": "前妻",
    "ex wife": "前妻",
    "ex-fiance": "前未婚夫",
    "ex-fiancee": "前未婚妻",
    "ex fiance": "前未婚夫",
    "ex fiancee": "前未婚妻",
    "betrayer": "背叛者",
    "traitor": "叛徒",
    "love interest": "情感对象",
    "business partner": "事业合伙人",
    "soul mate": "灵魂伴侣",
    "soulmate": "灵魂伴侣",
    "rival": "对手",
    "enemy": "敌人",
    "friend": "朋友",
    "mentor": "导师",
    "assistant": "助理",
    "servant": "仆从",
    "master": "主人",
    "subordinate": "下属",
    "superior": "上级",
    "colleague": "同事",
    "stepmother": "继母",
    "stepmother-in-law": "婆婆",
    "mother-in-law": "婆婆",
    "father-in-law": "公公",
    "son-in-law": "女婿",
    "daughter-in-law": "儿媳",
    "framer": "构陷者",
    "framed victim": "被构陷者",
    "control-obsessed mother": "控制型母亲",
    "control obsessed mother": "控制型母亲",
    "dependent son": "依附型儿子",
    "boss": "上位者",
    "exploited subordinate": "被剥削下属",
    "distant cousin": "远房亲戚",
    "mutual rival": "互竞对手",
    "victim": "受害者",
    "son": "儿子",
    "mother": "母亲",
    "cousin": "亲戚",
    "cousin / mutual rival": "远房亲戚 / 互竞对手",
    "core_content": "核心内容",
    "hook_opening": "开场钩子",
    "core_conflict": "核心冲突",
    "cliffhanger": "集末悬念",
    "check_result": "检查结果",
    "suggestion": "建议",
    "node_index": "节点序号",
    "emotion_tag": "情绪标签",
    "actual_value": "实际值",
    "target_value": "目标值",
    "deviation_gap": "偏差值",
    "trigger_event": "触发事件",
    "position_node_index": "节点位置",
    "emotion_peak_ev": "情绪峰值",
    "emotion_valley_et": "情绪低谷",
    "actual_emotion_nodes": "实际情绪节点",
    "deviation_nodes": "偏离节点",
    "emotion_tp": "转折点",
    "volume": "音量",
    "emotion": "情绪",
    "timestamp": "时间轴",
    "transition": "转场",
    "speech_speed": "语速",
    "episode_1": "第1集",
    "episode_2": "第2集",
    "episode_3": "第3集",
    # ── 合规九维 / 质量熔断 / 交付检查 ──
    "horror": "恐怖暴力",
    "minors": "未成年人保护",
    "values": "价值观",
    "copyright": "版权合规",
    "sensitive": "敏感内容",
    "false_info": "虚假信息",
    "crime_display": "犯罪呈现",
    "platform_red_line": "平台红线",
    "quality_check_result": "质量检查结果",
    "compliance_check_result": "合规检查结果",
    "suspend_reason": "暂缓原因",
    "trigger_suspend": "触发暂缓",
    "format_pass": "格式通过",
    "dream_safety_pass": "梦境安全通过",
    "level": "风险等级",
    "details": "详情",
    "role": "层级角色",
    "p0_risk_details": "P0 风险明细",
    "p1_risk_details": "P1 风险明细",
    "p2_optimization_suggestions": "P2 优化建议",
    "word_count_check_result": "字数检查结果",
    "over_deviation_episodes": "偏离集数",
    "episode_emotion_extraction": "分集情绪提取",
    "cognitive_gap_design": "认知差设计",
    "a_class_hooks": "A 类钩子",
    "report_version": "报告版本",
    # ── 市场分析报告 market-report.v1 ──
    "drama_basic_info": "剧目基础信息",
    "drama_name": "剧名",
    "core_genre": "核心题材",
    "platform_market_analysis": "平台市场分析",
    "target_audience_portrait": "目标受众画像",
    "Douyin_short_drama_current_trend": "抖音短剧当前趋势",
    "douyin_short_drama_current_trend": "抖音短剧当前趋势",
    "risk_warning_and_suggestion": "风险提示与建议",
    "content_risk_avoidance": "内容风险规避",
    "release_strategy_suggestion": "发行策略建议",
    "commercial_operation_forecast": "商业运营预测",
    "derivative_expansion_path": "衍生拓展路径",
    "expected_data_performance": "预期数据表现",
    "core_project_competitiveness_analysis": "项目竞争力分析",
    "IP_foundation": "IP 基础",
    "genre_matching_degree": "题材匹配度",
    # ── 市场分析报告 v3.1 复合结构 market-report.v1 ──
    "explosive_index": "爆款指数",
    "comprehensive_score": "综合得分",
    "level": "爆款等级",
    "dimension_detail": "维度明细",
    "hook_strength": "钩子强度",
    "track_matching": "赛道匹配",
    "emotional_depth": "情感深度",
    "conflict_handling": "冲突处理",
    "format_compliance": "格式合规",
    "cool_point_density": "爽点密度",
    "logical_consistency": "逻辑一致性",
    "narrative_efficiency": "叙事效率",
    "character_consistency": "人设一致性",
    "paid_point_optimization": "付费点优化",
    "hotspot_analysis": "热点分析",
    "user_portrait": "用户画像",
    "current_track_heat": "赛道热度",
    "platform_demand_spot": "平台需求点",
    "competitive_landscape": "竞争格局",
    "dream_three_indicators": "梦境三指标",
    "dream_sense_score": "梦境感",
    "pay_willingness_score": "付费意愿",
    "emotional_resonance_score": "情感共鸣",
    "six_dimensional_deconstruction": "六维拉片解构",
    "compliance_guard": "合规守护",
    "value_shift_design": "价值转变设计",
    "rule_execution_check": "规则执行校验",
    "episode_structure_verification": "分集结构校验",
    "narrative_efficiency_guarantee": "叙事效率保障",
    "reusable_templates": "可复用模板",
    # ── 立项简报 project-brief.v1 v3.1 ──
    "goal_conflict": "目标与冲突",
    "core_conflict": "核心冲突",
    "opening_stablish": "开篇建立",
    "cross_section_entry": "跨段入场",
    "rhythm_arrangement": "节奏编排",
    "rating": "钩子评级",
    "s_level": "S 级钩子",
    "a_level": "A 级钩子",
    "b_level": "B 级钩子",
    # ── 世界观 world-setting.v1 v3.1 ──
    "core_space": "核心空间",
    "core_rules": "核心规则",
    "forbidden_constraint": "禁忌约束",
    # ── 人物小传 character-bible.v1 v3.1 ──
    "core_supporting_roles": "核心配角",
    "total_relation_roles": "关系角色",
    "relationship_map": "人物关系",
    "dream_check": "梦境校验",
    "safety_score": "安全感得分",
    "is_blocking": "是否熔断",
    "timbre_tag": "音色标签",
    "visual_tag": "视觉标签",
    "Want": "表层欲望",
    "Need": "深层需求",
    "Ghost": "心魔",
    "Lie": "错误信念",
    "Flaw": "缺陷",
    "Douyin": "抖音",
    "douyin": "抖音",
    "ambition-transmigration-survival-fantasy": "野心穿越 · 生存玄幻",
    "ambition": "逆袭野心",
    "transmigration": "穿越",
    "survival": "生存",
    "fantasy": "玄幻",
}
