# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skill", "0026_strip_pipeline_skill_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='AgentRegistryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(default='default', max_length=64, unique=True, verbose_name='配置键')),
                ('display_name', models.CharField(blank=True, default='Agent 注册表', max_length=128, verbose_name='展示名称')),
                ('registry', models.JSONField(blank=True, default=dict, verbose_name='Agent Registry JSON')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='启用')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent 注册表配置',
                'verbose_name_plural': 'Agent 注册表配置',
                'db_table': 'skill_agent_registry_config',
                'ordering': ['-is_active', 'config_key'],
            },
        ),
        migrations.CreateModel(
            name='ReviewScoringConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(default='default', max_length=32, unique=True, verbose_name='配置键')),
                ('weights', models.JSONField(blank=True, default=dict, verbose_name='维度权重')),
                ('grade_thresholds', models.JSONField(blank=True, default=dict, verbose_name='等级阈值')),
                ('pass_threshold', models.PositiveSmallIntegerField(default=70, verbose_name='通过分数线')),
                ('min_sub_item_score', models.PositiveSmallIntegerField(default=75, verbose_name='子项最低分')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '质量审查评分',
                'verbose_name_plural': '质量审查评分',
                'db_table': 'skill_review_scoring_config',
            },
        ),
        migrations.CreateModel(
            name='AgentLlmRouteConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='路由键')),
                ('display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='展示名称')),
                ('max_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Tokens')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_llm_routes', to='skill.llmprovider', verbose_name='指定大模型')),
            ],
            options={
                'verbose_name': 'Agent LLM 路由',
                'verbose_name_plural': 'Agent LLM 路由',
                'db_table': 'skill_agent_llm_route',
                'ordering': ['sort_order', 'route_key'],
            },
        ),
            ],
        ),
    ]
