# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_independent_agent_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='knowledge_injection_policy',
            field=models.JSONField(blank=True, default=dict, help_text='可配置 excluded_categories(排除类别)、category_caps(各类别 Top-N)、max_total_chars(注入总字符预算)；留空使用全局默认策略', verbose_name='知识注入策略'),
        ),
        migrations.AddField(
            model_name='agentknowledgeitem',
            name='is_prompt_injectable',
            field=models.BooleanField(db_index=True, default=True, help_text='校验器/Schema 等仅供校验层使用的资产置 False，不进入 LLM 上下文', verbose_name='可注入 Prompt'),
        ),
        migrations.AddField(
            model_name='agentknowledgeitem',
            name='match_genres',
            field=models.JSONField(blank=True, default=list, verbose_name='适配类型'),
        ),
        migrations.AddField(
            model_name='agentknowledgeitem',
            name='match_platforms',
            field=models.JSONField(blank=True, default=list, verbose_name='适配平台'),
        ),
        migrations.AddField(
            model_name='agentknowledgeitem',
            name='match_themes',
            field=models.JSONField(blank=True, default=list, verbose_name='适配题材'),
        ),
    ]
