# Generated by Django 6.0.5 on 2026-06-19 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_knowledge_relevance_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewScoringPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preset_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='预设 ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='默认启用')),
                ('pass_threshold', models.PositiveSmallIntegerField(default=70, verbose_name='通过分数线')),
                ('min_sub_item_score', models.PositiveSmallIntegerField(default=75, verbose_name='子项最低分')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '审查评分预设',
                'verbose_name_plural': '审查评分预设',
                'db_table': 'agent_review_scoring_preset',
            },
        ),
        migrations.CreateModel(
            name='ReviewScoringDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension_key', models.CharField(db_index=True, max_length=32, verbose_name='维度')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='权重')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='agent.reviewscoringpreset')),
            ],
            options={
                'verbose_name': '审查评分维度',
                'verbose_name_plural': '审查评分维度',
                'db_table': 'agent_review_scoring_dimension',
                'unique_together': {('preset', 'dimension_key')},
            },
        ),
        migrations.CreateModel(
            name='ReviewGradeThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=8, verbose_name='等级')),
                ('min_score', models.PositiveSmallIntegerField(default=0, verbose_name='最低分')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_thresholds', to='agent.reviewscoringpreset')),
            ],
            options={
                'verbose_name': '审查等级阈值',
                'verbose_name_plural': '审查等级阈值',
                'db_table': 'agent_review_grade_threshold',
                'unique_together': {('preset', 'grade')},
            },
        ),
    ]
