export const API_SUCCESS_CODE = 0

export const API_ERROR_CODES = {
  SUCCESS: API_SUCCESS_CODE,
  BUSINESS_ERROR: 400,
  VALIDATION_ERROR: 4001,
  PARAM_MISSING: 4002,
  BUSINESS_CONFLICT: 4003,
  UNAUTHORIZED: 401,
  TOKEN_EXPIRED: 4011,
  PERMISSION_DENIED: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
  RATE_LIMITED: 42901,
  SIGNATURE_INVALID: 40101,
}

export const AUTH_ERROR_CODES = new Set([
  API_ERROR_CODES.UNAUTHORIZED,
  API_ERROR_CODES.TOKEN_EXPIRED,
])

export const PERMISSION_ERROR_CODES = new Set([API_ERROR_CODES.PERMISSION_DENIED])

export const RATE_LIMIT_ERROR_CODES = new Set([API_ERROR_CODES.RATE_LIMITED])
