# Generated by Django 6.0.5 on 2026-06-15 05:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('metric_type', models.CharField(choices=[('frontend_error_count', '前端异常数'), ('backend_error_count', '后端异常数'), ('api_avg_duration', '接口平均耗时'), ('api_error_rate', '接口错误率'), ('slow_sql_count', '慢 SQL 数')], db_index=True, max_length=64)),
                ('comparator', models.CharField(choices=[('gt', '大于'), ('gte', '大于等于'), ('lt', '小于'), ('lte', '小于等于')], default='gte', max_length=8)),
                ('threshold', models.FloatField()),
                ('window_minutes', models.PositiveIntegerField(default=5)),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], default='warning', max_length=16)),
                ('path_pattern', models.CharField(blank=True, default='', max_length=256)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('cooldown_minutes', models.PositiveIntegerField(default=10)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'sf_alert_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], db_index=True, max_length=16)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('message', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('open', '待处理'), ('acked', '已确认'), ('resolved', '已恢复')], db_index=True, default='open', max_length=16)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoring.alertrule')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
                'db_table': 'sf_alert_event',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiPerformanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('method', models.CharField(db_index=True, max_length=12)),
                ('status_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(db_index=True)),
                ('query_count', models.PositiveIntegerField(default=0)),
                ('slow_sql_count', models.PositiveIntegerField(default=0)),
                ('request_size', models.PositiveIntegerField(default=0)),
                ('response_size', models.PositiveIntegerField(default=0)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '接口性能日志',
                'verbose_name_plural': '接口性能日志',
                'db_table': 'sf_api_performance_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', '-created_at'], name='sf_api_perf_path_55c51d_idx'), models.Index(fields=['status_code', '-created_at'], name='sf_api_perf_status__58994c_idx'), models.Index(fields=['duration_ms', '-created_at'], name='sf_api_perf_duratio_924937_idx')],
            },
        ),
        migrations.CreateModel(
            name='FrontendEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('js_error', 'JS 错误'), ('resource_error', '资源加载错误'), ('promise_error', 'Promise 错误'), ('api_error', '接口异常'), ('performance', '页面性能'), ('page_view', '页面访问'), ('page_leave', '页面离开'), ('user_action', '用户行为'), ('custom', '自定义事件')], db_index=True, max_length=32)),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], db_index=True, default='info', max_length=16)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('page_url', models.CharField(blank=True, default='', max_length=1024)),
                ('route', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('browser', models.CharField(blank=True, default='', max_length=120)),
                ('os', models.CharField(blank=True, default='', max_length=120)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('performance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '前端监控事件',
                'verbose_name_plural': '前端监控事件',
                'db_table': 'sf_frontend_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='sf_frontend_event_t_a4d4d5_idx'), models.Index(fields=['level', '-created_at'], name='sf_frontend_level_e4d79c_idx'), models.Index(fields=['route', '-created_at'], name='sf_frontend_route_c06099_idx'), models.Index(fields=['session_id', '-created_at'], name='sf_frontend_session_5b1054_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('frontend', '前端'), ('backend', '后端')], db_index=True, max_length=16)),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], db_index=True, default='error', max_length=16)),
                ('exception_type', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('stack', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('method', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('status_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '异常记录',
                'verbose_name_plural': '异常记录',
                'db_table': 'sf_monitoring_exception',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='sf_monitori_source_e6ed8a_idx'), models.Index(fields=['level', '-created_at'], name='sf_monitori_level_bfeff5_idx'), models.Index(fields=['path', '-created_at'], name='sf_monitori_path_8a2af8_idx'), models.Index(fields=['fingerprint', '-created_at'], name='sf_monitori_fingerp_e7d647_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(db_index=True, default='ok', max_length=32)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '服务健康快照',
                'verbose_name_plural': '服务健康快照',
                'db_table': 'sf_service_health_snapshot',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['service_name', '-checked_at'], name='sf_service__service_d7a365_idx'), models.Index(fields=['status', '-checked_at'], name='sf_service__status_1e1003_idx')],
            },
        ),
        migrations.CreateModel(
            name='SqlPerformanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('method', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('sql', models.TextField(blank=True, default='')),
                ('sql_hash', models.CharField(db_index=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(db_index=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('stack', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '慢 SQL 日志',
                'verbose_name_plural': '慢 SQL 日志',
                'db_table': 'sf_sql_performance_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sql_hash', '-created_at'], name='sf_sql_perf_sql_has_888ca7_idx'), models.Index(fields=['duration_ms', '-created_at'], name='sf_sql_perf_duratio_7cd293_idx'), models.Index(fields=['path', '-created_at'], name='sf_sql_perf_path_ea7d68_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['metric_type', 'is_enabled'], name='sf_alert_ru_metric__7cf0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['is_enabled', '-created_at'], name='sf_alert_ru_is_enab_0e5edd_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['metric_type', '-triggered_at'], name='sf_alert_ev_metric__a1877e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['status', '-triggered_at'], name='sf_alert_ev_status_440bed_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['rule', '-triggered_at'], name='sf_alert_ev_rule_id_eb5432_idx'),
        ),
    ]
