# Generated by Cursor on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("frontend_error_count", "前端异常数"),
                    ("backend_error_count", "后端异常数"),
                    ("business_error_count", "业务 API 错误数"),
                    ("api_avg_duration", "接口平均耗时"),
                    ("api_error_rate", "接口错误率"),
                    ("slow_sql_count", "慢 SQL 数"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="frontendevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("js_error", "JS 错误"),
                    ("resource_error", "资源加载错误"),
                    ("promise_error", "Promise 错误"),
                    ("api_error", "接口异常"),
                    ("api_business_error", "业务接口失败"),
                    ("performance", "页面性能"),
                    ("page_view", "页面访问"),
                    ("page_leave", "页面离开"),
                    ("user_action", "用户行为"),
                    ("custom", "自定义事件"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="monitoringexception",
            name="source",
            field=models.CharField(
                choices=[
                    ("frontend", "前端"),
                    ("backend", "后端"),
                    ("business", "业务 API"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
