# Generated by Django 6.0.5 on 2026-06-11 09:41

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('phone', apps.users.models.EncryptedCharField(help_text='使用 AES-256-CBC 加密存储', max_length=255, verbose_name='手机号（加密）')),
                ('email', apps.users.models.EncryptedCharField(blank=True, default='', max_length=255, verbose_name='邮箱（加密）')),
                ('phone_hash', models.CharField(help_text='HMAC-SHA256，用于唯一索引与查询', max_length=64, unique=True, verbose_name='手机号哈希')),
                ('email_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='邮箱哈希')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500, verbose_name='头像URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否员工')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否超管')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='注册时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='资料ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500, verbose_name='头像URL')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他'), ('U', '未知')], default='U', max_length=1, verbose_name='性别')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='个人简介')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', '-created_at'], name='users_user_is_acti_35ce36_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_hash'], name='users_user_phone_h_0e8702_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_hash'], name='users_user_email_h_c3f9e3_idx'),
        ),
    ]
