# Generated by Django 6.0.5 on 2026-06-11 09:44

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=apps.users.models.EncryptedCharField(help_text='使用 AES-256-CBC 加密存储；唯一性由 phone_hash 在业务层保证', max_length=255, unique=True, verbose_name='手机号（加密）'),
        ),
    ]
