# Generated by Django 6.0.5 on 2026-06-11 09:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(db_index=True, help_text='唯一配置键名（例如 llm.api_key）', max_length=128, unique=True, verbose_name='配置键')),
                ('config_value_encrypted', models.TextField(blank=True, default='', help_text='AES-256-CBC 加密后的 base64 文本', verbose_name='加密后的配置值')),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='配置描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技能引擎配置',
                'verbose_name_plural': '技能引擎配置',
                'ordering': ['config_key'],
            },
        ),
        migrations.CreateModel(
            name='ThemeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme_code', models.CharField(db_index=True, help_text='英文唯一标识，例如 family-revenge', max_length=64, unique=True, verbose_name='题材代码')),
                ('theme_name', models.CharField(help_text='例如 家庭复仇', max_length=64, verbose_name='题材名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, help_text='数值越小越靠前', verbose_name='排序')),
                ('params', models.JSONField(blank=True, default=dict, help_text='包含 structure(结构)、reversal_density(反转密度)、emotion_curve(情绪曲线) 等', verbose_name='参数配置')),
                ('hook_templates', models.JSONField(blank=True, default=dict, help_text='按剧情阶段分类的钩子推荐配置', verbose_name='钩子模板配置')),
                ('character_archetypes', models.JSONField(blank=True, default=list, help_text='角色原型列表，包含名称、描述、标签等', verbose_name='角色原型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题材模板',
                'verbose_name_plural': '题材模板',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DialogueTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emotion_type', models.CharField(choices=[('happy', '开心'), ('sad', '悲伤'), ('angry', '愤怒'), ('anxious', '焦虑'), ('surprised', '惊讶'), ('fear', '恐惧'), ('romantic', '浪漫'), ('cold', '冷漠'), ('sarcastic', '讽刺'), ('gentle', '温柔'), ('domineering', '霸道'), ('mocking', '嘲讽'), ('firm', '坚定'), ('desperate', '绝望'), ('envy', '嫉妒')], db_index=True, default='happy', max_length=32, verbose_name='情绪类型')),
                ('template_text', models.TextField(help_text='对话文本，可包含 {speaker} {listener} {topic} 等占位符', verbose_name='模板文本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '对话模板',
                'verbose_name_plural': '对话模板',
                'ordering': ['-use_count', '-created_at'],
                'indexes': [models.Index(fields=['emotion_type', 'is_active'], name='skill_dialo_emotion_a15d64_idx')],
            },
        ),
        migrations.CreateModel(
            name='HookLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hook_type', models.CharField(choices=[('opening', '开场钩子'), ('reversal', '反转钩子'), ('suspense', '悬念钩子'), ('golden', '金句钩子'), ('climax', '高潮钩子'), ('ending', '结尾钩子')], db_index=True, default='opening', max_length=32, verbose_name='钩子类型')),
                ('content', models.TextField(help_text='钩子文本，可包含 {role} {name} 等占位符', verbose_name='钩子内容')),
                ('tags', models.CharField(blank=True, default='', help_text='逗号分隔的标签，例如 豪门,误会,身份反转', max_length=256, verbose_name='标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '钩子库',
                'verbose_name_plural': '钩子库',
                'ordering': ['-use_count', '-created_at'],
                'indexes': [models.Index(fields=['hook_type', 'is_active'], name='skill_hookl_hook_ty_632b49_idx')],
            },
        ),
    ]
