# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-12 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_llmmodelcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionPipelinePack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='技能版本')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='当前启用')),
                ('terminal_node_ids', models.JSONField(blank=True, default=list, verbose_name='终止节点 ID 列表')),
                ('project_meta', models.JSONField(blank=True, default=dict, verbose_name='projectMeta 快照')),
                ('imported_from_root', models.CharField(blank=True, default='', max_length=512, verbose_name='导入来源路径')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '融合流水线配置包',
                'verbose_name_plural': '融合流水线配置包',
                'db_table': 'skill_fusion_pipeline_pack',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FusionJsonSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_key', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Schema 键')),
                ('filename', models.CharField(max_length=128, verbose_name='文件名')),
                ('schema_json', models.JSONField(verbose_name='Schema JSON')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='skill.fusionpipelinepack', verbose_name='所属配置包')),
            ],
            options={
                'verbose_name': '融合 JSON Schema',
                'verbose_name_plural': '融合 JSON Schema',
                'db_table': 'skill_fusion_json_schema',
                'ordering': ['schema_key'],
            },
        ),
        migrations.CreateModel(
            name='FusionPipelineNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fusion_node_id', models.CharField(db_index=True, max_length=64, verbose_name='融合节点 ID')),
                ('chain_order', models.PositiveSmallIntegerField(verbose_name='主链顺序')),
                ('website_index', models.PositiveSmallIntegerField(verbose_name='网站步骤序号')),
                ('name', models.CharField(max_length=128, verbose_name='节点名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('sub_skill', models.CharField(blank=True, default='', max_length=64, verbose_name='子技能')),
                ('output_key', models.CharField(blank=True, default='', max_length=64, verbose_name='产物键 outputKey')),
                ('artifact_key', models.CharField(blank=True, default='', max_length=64, verbose_name='存储 artifact_key')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='终止节点')),
                ('fusion_status', models.CharField(blank=True, default='', max_length=32, verbose_name='项目状态映射')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_nodes', to='skill.fusionjsonschema', verbose_name='JSON Schema')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='skill.fusionpipelinepack', verbose_name='配置包')),
            ],
            options={
                'verbose_name': '融合流水线节点',
                'verbose_name_plural': '融合流水线节点',
                'db_table': 'skill_fusion_pipeline_node',
                'ordering': ['chain_order'],
                'constraints': [models.UniqueConstraint(fields=('pack', 'fusion_node_id'), name='uniq_fusion_pack_node_id'), models.UniqueConstraint(fields=('pack', 'chain_order'), name='uniq_fusion_pack_chain_order')],
            },
        ),
    ]
