# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0014_skill_rule_config'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='llmusagelog',
            new_name='skill_llm_u_created_e98b13_idx',
            old_name='skill_llm_u_created_8a1b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='llmusagelog',
            new_name='skill_llm_u_created_88e013_idx',
            old_name='skill_llm_u_created_9b2c1e_idx',
        ),
        migrations.AlterField(
            model_name='agentllmrouteconfig',
            name='llm_provider',
            field=models.ForeignKey(blank=True, help_text='仅辅助 Agent 需要；主链节点请在融合节点配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_llm_routes', to='skill.llmprovider', verbose_name='指定大模型'),
        ),
        migrations.AlterField(
            model_name='fusionnodellmpromptconfig',
            name='llm_provider',
            field=models.ForeignKey(blank=True, help_text='留空则使用全局激活的大模型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusion_node_prompts', to='skill.llmprovider', verbose_name='指定大模型'),
        ),
    ]
