# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0015_rename_skill_llm_u_created_8a1b0d_idx_skill_llm_u_created_e98b13_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegistryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(default='default', max_length=64, unique=True, verbose_name='配置键')),
                ('display_name', models.CharField(blank=True, default='Agent 注册表', max_length=128, verbose_name='展示名称')),
                ('registry', models.JSONField(blank=True, default=dict, help_text='结构对齐 demo4book/agents/registry.json；可配置 agents、workspace_modules、post_script_chain 等', verbose_name='Agent Registry JSON')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='启用')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent 注册表配置',
                'verbose_name_plural': 'Agent 注册表配置',
                'db_table': 'skill_agent_registry_config',
                'ordering': ['-is_active', 'config_key'],
            },
        ),
    ]
