# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 06:08

from django.db import migrations, models


def backfill_review_extra_artifacts(apps, schema_editor):
    FusionPipelineNode = apps.get_model('skill', 'FusionPipelineNode')
    FusionPipelineNode.objects.filter(
        fusion_node_id='node-6-review',
        extra_artifact_keys=[],
    ).update(extra_artifact_keys=['gate_full', 'compliance'])


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0016_agentregistryconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusionpipelinenode',
            name='extra_artifact_keys',
            field=models.JSONField(blank=True, default=list, help_text='多产物节点使用，如质检节点可配置 gate_full/compliance 等额外产物', verbose_name='额外 artifact_key 列表'),
        ),
        migrations.RunPython(backfill_review_extra_artifacts, migrations.RunPython.noop),
    ]
