# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 06:21

from django.db import migrations, models


def backfill_runner_type(apps, schema_editor):
    FusionPipelineNode = apps.get_model('skill', 'FusionPipelineNode')
    FusionPipelineNode.objects.filter(website_index__lte=5, runner_type='').update(
        runner_type='fusion_node'
    )
    FusionPipelineNode.objects.filter(fusion_node_id='node-6-review', runner_type='').update(
        runner_type='fusion_review'
    )
    FusionPipelineNode.objects.filter(fusion_node_id='node-8-score', runner_type='').update(
        runner_type='fusion_score'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0017_fusionpipelinenode_extra_artifact_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusionpipelinenode',
            name='runner_type',
            field=models.CharField(blank=True, choices=[('fusion_node', '融合主链节点'), ('fusion_review', '融合质检'), ('fusion_score', '融合评分'), ('agent_chain', 'Agent 后处理链')], default='', help_text='控制分步执行时使用哪类 runner；留空时按旧 node_index 规则兜底', max_length=32, verbose_name='执行器类型'),
        ),
        migrations.RunPython(backfill_runner_type, migrations.RunPython.noop),
    ]
