# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 06:58

from django.db import migrations, models


def backfill_runner_path(apps, schema_editor):
    FusionPipelineNode = apps.get_model('skill', 'FusionPipelineNode')
    FusionPipelineNode.objects.filter(website_index__lte=5, runner_path='').update(
        runner_path='apps.creation.step_mode.run_orchestrator_step'
    )
    FusionPipelineNode.objects.filter(fusion_node_id='node-6-review', runner_path='').update(
        runner_path='apps.creation.step_mode.run_fusion_review_step'
    )
    FusionPipelineNode.objects.filter(fusion_node_id='node-8-score', runner_path='').update(
        runner_path='apps.creation.step_mode.run_fusion_score_step'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0018_fusionpipelinenode_runner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusionpipelinenode',
            name='runner_path',
            field=models.CharField(blank=True, default='', help_text='如 apps.creation.step_mode.run_orchestrator_step；仅允许受信任模块路径', max_length=255, verbose_name='执行函数路径'),
        ),
        migrations.RunPython(backfill_runner_path, migrations.RunPython.noop),
    ]
