# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0020_fusionpipelinenode_pipeline_result_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillruleconfig',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tier1·全局铁律'), (2, 'Tier2·品类规范'), (3, 'Tier3·节点流程'), (4, 'Tier4·合规熔断')], db_index=True, verbose_name='层级'),
        ),
    ]
