# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14

from django.db import migrations, models

from apps.workflow.tier1_sections import DEFAULT_TIER1_SECTIONS_BY_NODE


def backfill_tier1_sections(apps, schema_editor):
    FusionPipelineNode = apps.get_model("skill", "FusionPipelineNode")
    for fusion_node_id, sections in DEFAULT_TIER1_SECTIONS_BY_NODE.items():
        FusionPipelineNode.objects.filter(
            fusion_node_id=fusion_node_id,
            tier1_sections=[],
        ).update(tier1_sections=sections)


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0021_alter_skillruleconfig_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="tier1_sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="LLM 组装 system prompt 时从 Tier1 铁律提取的 section 名列表",
                verbose_name="Tier1 注入分区",
            ),
        ),
        migrations.RunPython(backfill_tier1_sections, migrations.RunPython.noop),
    ]
