# Generated by Django 6.0.5 on 2026-06-14

from django.db import migrations, models
import django.db.models.deletion

from apps.skill.config.bootstrap.workflow_disk import DEFAULT_STEP_OPS_BY_NODE


def merge_legacy_step_config(apps, schema_editor):
    FusionPipelinePack = apps.get_model("skill", "FusionPipelinePack")
    FusionPipelineNode = apps.get_model("skill", "FusionPipelineNode")
    PipelineNodeConfig = apps.get_model("billing", "PipelineNodeConfig")
    FusionNodeLlmPromptConfig = apps.get_model("skill", "FusionNodeLlmPromptConfig")

    pack = FusionPipelinePack.objects.filter(is_active=True).order_by("-updated_at").first()
    if not pack:
        return

    billing_by_fid = {row.fusion_node_id: row for row in PipelineNodeConfig.objects.all()}
    prompt_by_fid = {row.node_id: row for row in FusionNodeLlmPromptConfig.objects.all()}

    for node in FusionPipelineNode.objects.filter(pack=pack):
        billing = billing_by_fid.get(node.fusion_node_id)
        prompt = prompt_by_fid.get(node.fusion_node_id)
        ops = DEFAULT_STEP_OPS_BY_NODE.get(node.fusion_node_id, {})

        if billing:
            node.name = (billing.display_name or node.name)[:128]
            node.enabled = billing.enabled
            node.requires_confirm = billing.requires_confirm
            node.portal_visible = billing.portal_visible
            node.coin_cost = billing.coin_cost
        else:
            node.coin_cost = ops.get("coin_cost", node.coin_cost)
            node.portal_visible = ops.get("portal_visible", node.portal_visible)

        if prompt:
            node.system_prompt = prompt.system_prompt or ""
            node.user_prompt_tpl = prompt.user_prompt_tpl or ""
            node.prompt_constraints = prompt.constraints or ""
            node.prompt_enabled = prompt.is_active
            node.max_tokens = prompt.max_tokens
            node.llm_provider_id = prompt.llm_provider_id

        node.save()


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0022_fusionpipelinenode_tier1_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="coin_cost",
            field=models.PositiveIntegerField(default=10, verbose_name="单步币价"),
        ),
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="启用"),
        ),
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="llm_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fusion_pipeline_nodes",
                to="skill.llmprovider",
                verbose_name="指定大模型",
            ),
        ),
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="max_tokens",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Max Tokens"),
        ),
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="portal_visible",
            field=models.BooleanField(default=True, verbose_name="C 端展示"),
        ),
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="prompt_constraints",
            field=models.TextField(blank=True, default="", verbose_name="附加约束"),
        ),
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="prompt_enabled",
            field=models.BooleanField(default=True, verbose_name="启用节点提示词"),
        ),
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="requires_confirm",
            field=models.BooleanField(default=True, verbose_name="分步需确认"),
        ),
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="system_prompt",
            field=models.TextField(blank=True, default="", verbose_name="System 提示词"),
        ),
        migrations.AddField(
            model_name="fusionpipelinenode",
            name="user_prompt_tpl",
            field=models.TextField(
                blank=True,
                default="",
                help_text="占位符：{upstream_json}",
                verbose_name="User 模板",
            ),
        ),
        migrations.RunPython(merge_legacy_step_config, migrations.RunPython.noop),
    ]
