# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-15 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0027_remove_agentllmrouteconfig_llm_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSkillDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(db_index=True, help_text='如 drama-master-suite / drama-creator-core', max_length=100, unique=True, verbose_name='技能 ID')),
                ('name', models.CharField(max_length=200, verbose_name='技能名称')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='版本号')),
                ('category', models.CharField(choices=[('creator', '创作类'), ('quality', '质检类'), ('compliance', '合规类'), ('shared', '通用共享')], db_index=True, default='creator', max_length=50, verbose_name='分类')),
                ('content', models.TextField(help_text='原始 SKILL.md 的完整 Markdown 内容', verbose_name='技能内容（Markdown）')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('source_file', models.CharField(blank=True, help_text='迁移前的本地相对路径，如 ai-drama-skills-v2/drama-creator-core/SKILL.md', max_length=300, verbose_name='来源文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Agent 技能定义',
                'verbose_name_plural': 'Agent 技能定义',
                'db_table': 'skill_agent_definition',
                'ordering': ['category', 'skill_id'],
            },
        ),
        migrations.CreateModel(
            name='SkillConfigEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(db_index=True, help_text='如 skill-thresholds / qdn-emotion-engine', max_length=100, unique=True, verbose_name='配置键')),
                ('edition', models.CharField(default='unified', help_text='如 unified / demo4book / ai-drama-skills-v2', max_length=20, verbose_name='版本/版型')),
                ('content', models.JSONField(verbose_name='配置内容')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='版本号')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技能配置项',
                'verbose_name_plural': '技能配置项',
                'db_table': 'skill_config_entry',
                'ordering': ['config_key'],
            },
        ),
        migrations.CreateModel(
            name='SkillDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('severity', models.CharField(choices=[('P0', 'P0-阻断'), ('P1', 'P1-严重'), ('P2', 'P2-一般'), ('P3', 'P3-改进')], db_index=True, default='P2', max_length=5, verbose_name='严重级别')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '关闭')], db_index=True, default='open', max_length=20, verbose_name='状态')),
                ('reproduce_steps', models.TextField(blank=True, verbose_name='复现步骤')),
                ('fix_notes', models.TextField(blank=True, verbose_name='修复说明')),
                ('reported_by', models.CharField(blank=True, max_length=100, verbose_name='报告人')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='skill.agentskilldefinition', verbose_name='所属技能')),
            ],
            options={
                'verbose_name': '技能缺陷',
                'verbose_name_plural': '技能缺陷',
                'db_table': 'skill_defect',
                'ordering': ['severity', '-created_at'],
                'indexes': [models.Index(fields=['skill', 'status'], name='skill_defect_skill_status_idx'), models.Index(fields=['severity', 'status'], name='skill_defect_severity_idx')],
            },
        ),
    ]
