# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-19 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0038_skillruleconfig_content_source_entry_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSkillSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.CharField(choices=[('system_prompt', 'System Prompt'), ('input_schema', 'Input Schema'), ('quality_checklist', 'Quality Checklist'), ('anti_patterns', 'Anti Patterns'), ('examples', 'Examples')], db_index=True, max_length=64, verbose_name='分区键')),
                ('section_content', models.TextField(blank=True, default='', verbose_name='分区内容')),
                ('section_schema_json', models.JSONField(blank=True, default=dict, verbose_name='Schema JSON')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Agent 技能分区',
                'verbose_name_plural': 'Agent 技能分区',
                'db_table': 'skill_agent_skill_section',
                'ordering': ['skill_id', 'sort_order', 'section_key'],
            },
        ),
        migrations.CreateModel(
            name='ThemeActRatio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('act_name', models.CharField(max_length=64, verbose_name='幕名称')),
                ('ratio_percent', models.PositiveSmallIntegerField(default=0, verbose_name='占比%')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '题材幕占比',
                'verbose_name_plural': '题材幕占比',
                'db_table': 'skill_theme_act_ratio',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ThemeCharacterArchetype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='原型名')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('fit_genres', models.JSONField(blank=True, default=list, verbose_name='适用题材')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '题材角色原型',
                'verbose_name_plural': '题材角色原型',
                'db_table': 'skill_theme_character_archetype',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ThemeEmotionalPeakMoment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_hint', models.CharField(blank=True, default='', max_length=64, verbose_name='集数提示')),
                ('moment', models.TextField(verbose_name='峰值时刻')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '题材情绪峰值',
                'verbose_name_plural': '题材情绪峰值',
                'db_table': 'skill_theme_emotional_peak',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ThemeEmotionCurve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_from', models.PositiveSmallIntegerField(default=1, verbose_name='起始集')),
                ('episode_to', models.PositiveSmallIntegerField(default=1, verbose_name='结束集')),
                ('emotion_value', models.SmallIntegerField(default=0, verbose_name='情绪值')),
                ('label', models.CharField(blank=True, default='', max_length=64, verbose_name='标签')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '题材情绪曲线',
                'verbose_name_plural': '题材情绪曲线',
                'db_table': 'skill_theme_emotion_curve',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ThemeHookType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hook_type', models.CharField(max_length=64, verbose_name='钩子类型')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '题材钩子类型',
                'verbose_name_plural': '题材钩子类型',
                'db_table': 'skill_theme_hook_type',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ThemeReversalDensity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=64, verbose_name='阶段')),
                ('density', models.CharField(blank=True, default='', max_length=32, verbose_name='密度')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '题材反转密度',
                'verbose_name_plural': '题材反转密度',
                'db_table': 'skill_theme_reversal_density',
                'ordering': ['sort_order'],
            },
        ),
        migrations.RenameIndex(
            model_name='ruleevolutionproposal',
            new_name='skill_rulee_status_27cb60_idx',
            old_name='skill_proposal_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ruleevolutionproposal',
            new_name='skill_rulee_trigger_a50bd5_idx',
            old_name='skill_proposal_trigger_idx',
        ),
        migrations.RenameIndex(
            model_name='ruleevolutionproposal',
            new_name='skill_rulee_target__a4787e_idx',
            old_name='skill_proposal_target_idx',
        ),
        migrations.AddField(
            model_name='hooklibrary',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='hooklibrary',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='hooklibrary',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hooks', to='skill.themetemplate', verbose_name='关联题材'),
        ),
        migrations.AddField(
            model_name='themetemplate',
            name='audience_fit',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='受众定位'),
        ),
        migrations.AddField(
            model_name='themetemplate',
            name='core_conflict_formula',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='核心冲突公式'),
        ),
        migrations.AddField(
            model_name='themetemplate',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='题材描述'),
        ),
        migrations.AddField(
            model_name='themetemplate',
            name='recommended_episodes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='推荐集数'),
        ),
        migrations.AlterField(
            model_name='agentskilldefinition',
            name='skill_id',
            field=models.CharField(db_index=True, help_text='如 drama-master-suite / brief.character_extract', max_length=100, unique=True, verbose_name='技能 ID'),
        ),
        migrations.AlterField(
            model_name='agentskilldefinition',
            name='source_file',
            field=models.CharField(blank=True, help_text='迁移前的本地相对路径，如 legacy-skills/drama-creator-core/SKILL.md', max_length=300, verbose_name='来源文件路径'),
        ),
        migrations.AlterField(
            model_name='ruleevolutionproposal',
            name='change_reason',
            field=models.TextField(blank=True, default='', help_text='AI 或人工提出的修改理由', verbose_name='修改理由'),
        ),
        migrations.AlterField(
            model_name='ruleevolutionproposal',
            name='current_value',
            field=models.JSONField(blank=True, default=dict, help_text='规则修改前的当前值', verbose_name='当前值'),
        ),
        migrations.AlterField(
            model_name='ruleevolutionproposal',
            name='proposed_value',
            field=models.JSONField(blank=True, default=dict, help_text='建议修改为目标的值', verbose_name='提案值'),
        ),
        migrations.AlterField(
            model_name='ruleevolutionproposal',
            name='target_scope_key',
            field=models.CharField(blank=True, default='', help_text='题材代码（如 family-revenge）或节点 ID（如 node-5-script）', max_length=100, verbose_name='目标范围'),
        ),
        migrations.AlterField(
            model_name='ruleevolutionproposal',
            name='target_skill_id',
            field=models.CharField(blank=True, default='', help_text='如 drama-master-suite', max_length=100, verbose_name='目标技能'),
        ),
        migrations.AlterField(
            model_name='ruleevolutionproposal',
            name='target_tier',
            field=models.CharField(blank=True, default='', help_text='如 Tier2 / Tier3', max_length=20, verbose_name='目标规则层'),
        ),
        migrations.AlterField(
            model_name='ruleevolutionproposal',
            name='trigger_project_id',
            field=models.UUIDField(blank=True, help_text='触发本次提案的低评分项目 ID', null=True, verbose_name='触发项目'),
        ),
        migrations.AlterField(
            model_name='ruleevolutionproposal',
            name='trigger_reason',
            field=models.CharField(blank=True, default='', help_text='如：连续3个项目在人物塑造维度低于70分', max_length=200, verbose_name='触发原因'),
        ),
        migrations.AlterField(
            model_name='skillconfigentry',
            name='edition',
            field=models.CharField(default='unified', help_text='如 unified / legacy-demo / legacy-skills', max_length=20, verbose_name='版本/版型'),
        ),
        migrations.AddConstraint(
            model_name='skillruleconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tier', 'scope_type', 'scope_key', 'section'), name='skill_rule_config_active_scope_uniq'),
        ),
        migrations.AddField(
            model_name='agentskillsection',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='skill.agentskilldefinition', verbose_name='技能'),
        ),
        migrations.AddField(
            model_name='themeactratio',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_ratios', to='skill.themetemplate'),
        ),
        migrations.AddField(
            model_name='themecharacterarchetype',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='skill.themetemplate'),
        ),
        migrations.AddField(
            model_name='themeemotionalpeakmoment',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peak_moments', to='skill.themetemplate'),
        ),
        migrations.AddField(
            model_name='themeemotioncurve',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_curves', to='skill.themetemplate'),
        ),
        migrations.AddField(
            model_name='themehooktype',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hook_types', to='skill.themetemplate'),
        ),
        migrations.AddField(
            model_name='themereversaldensity',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_densities', to='skill.themetemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='agentskillsection',
            unique_together={('skill', 'section_key')},
        ),
    ]
