# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-19 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0039_skill_agent_catalog_atomic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeSettingsConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(default='default', max_length=32, unique=True, verbose_name='配置键')),
                ('min_episodes', models.PositiveSmallIntegerField(default=20, verbose_name='最少集数')),
                ('max_episodes', models.PositiveSmallIntegerField(default=200, verbose_name='最多集数')),
                ('step', models.PositiveSmallIntegerField(default=10, verbose_name='步进')),
                ('default_episodes', models.PositiveSmallIntegerField(default=80, verbose_name='默认集数')),
                ('presets', models.JSONField(blank=True, default=list, verbose_name='快捷预设')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=2, verbose_name='单集时长(分)')),
            ],
            options={
                'verbose_name': '集数设置',
                'verbose_name_plural': '集数设置',
                'db_table': 'skill_episode_settings_config',
            },
        ),
        migrations.CreateModel(
            name='CreationBudgetLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(db_index=True, default='default', max_length=32, verbose_name='配置键')),
                ('item_key', models.CharField(db_index=True, max_length=64, verbose_name='预算键')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '创作预算档位',
                'verbose_name_plural': '创作预算档位',
                'db_table': 'skill_creation_budget_level',
                'ordering': ['sort_order', 'item_key'],
                'unique_together': {('config_key', 'item_key')},
            },
        ),
        migrations.CreateModel(
            name='CreationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(db_index=True, default='default', max_length=32, verbose_name='配置键')),
                ('item_key', models.CharField(db_index=True, max_length=64, verbose_name='入口键')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '创作入口',
                'verbose_name_plural': '创作入口',
                'db_table': 'skill_creation_entry',
                'ordering': ['sort_order', 'item_key'],
                'unique_together': {('config_key', 'item_key')},
            },
        ),
        migrations.CreateModel(
            name='CreationEntryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(db_index=True, default='default', max_length=32, verbose_name='配置键')),
                ('entry_key', models.CharField(db_index=True, max_length=64, verbose_name='入口键')),
                ('profile', models.JSONField(blank=True, default=dict, verbose_name='Profile 配置')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '创作入口 Profile',
                'verbose_name_plural': '创作入口 Profile',
                'db_table': 'skill_creation_entry_profile',
                'unique_together': {('config_key', 'entry_key')},
            },
        ),
        migrations.CreateModel(
            name='CreationPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(db_index=True, default='default', max_length=32, verbose_name='配置键')),
                ('item_key', models.CharField(db_index=True, max_length=64, verbose_name='平台键')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '创作平台',
                'verbose_name_plural': '创作平台',
                'db_table': 'skill_creation_platform',
                'ordering': ['sort_order', 'item_key'],
                'unique_together': {('config_key', 'item_key')},
            },
        ),
        migrations.CreateModel(
            name='CreationThemeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(db_index=True, default='default', max_length=32, verbose_name='配置键')),
                ('theme_key', models.CharField(db_index=True, max_length=64, verbose_name='题材键')),
                ('display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='展示名')),
                ('recommended_episodes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='推荐集数')),
                ('recommended_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='推荐时长(分)')),
                ('color', models.CharField(blank=True, default='#667eea', max_length=16, verbose_name='颜色')),
                ('icon', models.CharField(blank=True, default='🎬', max_length=32, verbose_name='图标')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '创作题材入口',
                'verbose_name_plural': '创作题材入口',
                'db_table': 'skill_creation_theme_entry',
                'ordering': ['sort_order', 'theme_key'],
                'unique_together': {('config_key', 'theme_key')},
            },
        ),
        migrations.CreateModel(
            name='FormatVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(db_index=True, default='default', max_length=32, verbose_name='配置键')),
                ('item_key', models.CharField(db_index=True, max_length=8, verbose_name='格式键')),
                ('schema_key', models.CharField(blank=True, default='', max_length=32, verbose_name='Schema 键')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('scene_heading', models.CharField(blank=True, default='', max_length=128, verbose_name='场景标题样例')),
                ('dialogue_marker', models.CharField(blank=True, default='', max_length=64, verbose_name='台词标记')),
                ('action_marker', models.CharField(blank=True, default='', max_length=64, verbose_name='动作标记')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '剧本格式变体',
                'verbose_name_plural': '剧本格式变体',
                'db_table': 'skill_creation_format_variant',
                'ordering': ['sort_order', 'item_key'],
                'unique_together': {('config_key', 'item_key')},
            },
        ),
    ]
