# Generated by Django 6.0.5 on 2026-06-16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creation', '0015_project_gray_flow_version'),
        ('workflow', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任务ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('paused', '已暂停')], default='pending', max_length=20, verbose_name='状态')),
                ('csv_data', models.JSONField(default=list, verbose_name='CSV 数据')),
                ('total_count', models.IntegerField(default=0, verbose_name='总项目数')),
                ('completed_count', models.IntegerField(default=0, verbose_name='已完成')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('pipeline_pack_id', models.UUIDField(blank=True, null=True, verbose_name='工作流包 ID')),
                ('theme', models.CharField(max_length=64, verbose_name='题材')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '批量创作任务',
                'verbose_name_plural': '批量创作任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='子项目ID')),
                ('row_index', models.IntegerField(verbose_name='CSV 行号')),
                ('core_idea', models.TextField(verbose_name='核心创意')),
                ('extra_params', models.JSONField(default=dict, verbose_name='额外参数')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_projects', to='batch.batchjob', verbose_name='所属批量任务')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_sub_project', to='creation.project', verbose_name='创作项目')),
            ],
            options={
                'verbose_name': '批量创作子项目',
                'verbose_name_plural': '批量创作子项目',
                'ordering': ['row_index'],
            },
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['user', '-created_at'], name='batch_job_user_id_d4a0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['status'], name='batch_job_status_7c3f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchproject',
            index=models.Index(fields=['batch_job', 'status'], name='batch_proj_batch__5e8c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='batchproject',
            index=models.Index(fields=['row_index'], name='batch_proj_row_inde_b9f6d2_idx'),
        ),
    ]
