# Generated by Cursor Agent
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfigCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="分类编码")),
                ("name", models.CharField(max_length=80, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, default="", verbose_name="分类说明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "配置分类",
                "verbose_name_plural": "配置分类",
                "db_table": "system_config_category",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfigItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("config_key", models.CharField(db_index=True, max_length=160, unique=True, verbose_name="配置键")),
                ("config_name", models.CharField(max_length=120, verbose_name="配置名称")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "字符串"),
                            ("int", "整数"),
                            ("float", "浮点数"),
                            ("bool", "布尔"),
                            ("json", "JSON对象"),
                            ("array", "JSON数组"),
                        ],
                        max_length=16,
                        verbose_name="值类型",
                    ),
                ),
                ("value", models.JSONField(blank=True, default=None, null=True, verbose_name="配置值")),
                ("default_value", models.JSONField(blank=True, default=None, null=True, verbose_name="默认值")),
                ("description", models.TextField(blank=True, default="", verbose_name="备注")),
                ("validation_schema", models.JSONField(blank=True, default=dict, verbose_name="校验规则")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="启用")),
                ("is_sensitive", models.BooleanField(db_index=True, default=False, verbose_name="敏感配置")),
                ("is_public", models.BooleanField(db_index=True, default=False, verbose_name="公开读取")),
                ("requires_restart", models.BooleanField(default=False, verbose_name="需要重启")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="版本号")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="删除时间")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="system_config.systemconfigcategory",
                        verbose_name="配置分类",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_system_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_system_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置项",
                "verbose_name_plural": "配置项",
                "db_table": "system_config_item",
                "ordering": ["category__sort_order", "config_key"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfigAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("config_key", models.CharField(db_index=True, max_length=160, verbose_name="配置键")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "新增"),
                            ("update", "更新"),
                            ("toggle", "启用禁用"),
                            ("delete", "删除"),
                            ("refresh_cache", "刷新缓存"),
                            ("restore_default", "恢复默认"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="操作",
                    ),
                ),
                ("old_value", models.JSONField(blank=True, null=True, verbose_name="旧值")),
                ("new_value", models.JSONField(blank=True, null=True, verbose_name="新值")),
                ("change_reason", models.CharField(blank=True, default="", max_length=300, verbose_name="变更原因")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                ("user_agent", models.CharField(blank=True, default="", max_length=512, verbose_name="User-Agent")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="创建时间")),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="system_config.systemconfigitem",
                        verbose_name="配置项",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_config_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置变更日志",
                "verbose_name_plural": "配置变更日志",
                "db_table": "system_config_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="systemconfigcategory",
            index=models.Index(fields=["is_active", "sort_order"], name="system_conf_is_acti_2cfb16_idx"),
        ),
        migrations.AddIndex(
            model_name="systemconfigitem",
            index=models.Index(fields=["category", "is_active"], name="system_conf_categor_44e117_idx"),
        ),
        migrations.AddIndex(
            model_name="systemconfigitem",
            index=models.Index(fields=["is_public", "is_active"], name="system_conf_is_publ_d76e84_idx"),
        ),
        migrations.AddIndex(
            model_name="systemconfigitem",
            index=models.Index(fields=["updated_at"], name="system_conf_updated_73be95_idx"),
        ),
        migrations.AddIndex(
            model_name="systemconfigitem",
            index=models.Index(fields=["deleted_at", "is_active"], name="system_conf_deleted_6d2213_idx"),
        ),
        migrations.AddIndex(
            model_name="systemconfigauditlog",
            index=models.Index(fields=["config_key", "-created_at"], name="system_conf_config__ccbff0_idx"),
        ),
        migrations.AddIndex(
            model_name="systemconfigauditlog",
            index=models.Index(fields=["action", "-created_at"], name="system_conf_action_a11862_idx"),
        ),
    ]
