# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-11 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='全局唯一的日志记录ID', primary_key=True, serialize=False, verbose_name='日志ID')),
                ('user_id', models.BigIntegerField(blank=True, db_index=True, help_text='关联用户ID，未登录用户为空', null=True, verbose_name='用户ID')),
                ('action', models.CharField(choices=[('login', '用户登录'), ('logout', '用户登出'), ('register', '用户注册'), ('create', '创建资源'), ('read', '读取资源'), ('update', '更新资源'), ('delete', '删除资源'), ('download', '下载资源'), ('export', '导出资源'), ('payment', '支付操作'), ('admin', '后台管理'), ('api_call', 'API 调用'), ('signature_fail', '签名验证失败'), ('rate_limit', '触发限流'), ('permission_deny', '权限拒绝'), ('data_leak', '疑似数据泄露'), ('other', '其他操作')], db_index=True, default='api_call', help_text='本次请求/操作的类型枚举', max_length=32, verbose_name='操作类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='请求来源IP地址', null=True, verbose_name='客户端IP')),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, help_text='客户端设备指纹，用于设备识别与反作弊', max_length=255, null=True, verbose_name='设备指纹')),
                ('request_path', models.CharField(db_index=True, help_text='HTTP 请求路径 (PATH_INFO)', max_length=512, verbose_name='请求路径')),
                ('request_method', models.CharField(db_index=True, help_text='HTTP 请求方法，如 GET / POST / PUT / DELETE', max_length=10, verbose_name='请求方法')),
                ('request_hash', models.CharField(blank=True, help_text='请求体 SHA-256 哈希值，便于追溯请求内容', max_length=64, null=True, verbose_name='请求体Hash')),
                ('response_status', models.IntegerField(blank=True, db_index=True, help_text='HTTP 响应状态码', null=True, verbose_name='响应状态码')),
                ('extra_info', models.JSONField(blank=True, default=dict, help_text='额外的上下文信息，存储为 JSON', null=True, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='日志记录时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'sf_audit_log',
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='sf_audit_lo_user_id_0c239f_idx'), models.Index(fields=['ip_address', '-created_at'], name='sf_audit_lo_ip_addr_ca69a5_idx'), models.Index(fields=['action', '-created_at'], name='sf_audit_lo_action_eb2c16_idx'), models.Index(fields=['response_status', '-created_at'], name='sf_audit_lo_respons_1a37bf_idx'), models.Index(fields=['device_fingerprint', '-created_at'], name='sf_audit_lo_device__e2c3f2_idx')],
            },
        ),
    ]
