# Generated by Django 6.0.5 on 2026-06-11 09:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='价格(元)')),
                ('validity_days', models.IntegerField(default=30, verbose_name='有效期(天)')),
                ('creation_quota', models.IntegerField(default=-1, help_text='-1 表示无限创作', verbose_name='创作次数配额')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='套餐特性')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('sort_order', models.IntegerField(default=0, help_text='数值越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '会员套餐',
                'verbose_name_plural': '会员套餐',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='卡密')),
                ('max_uses', models.IntegerField(default=1, verbose_name='最大使用次数')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_codes', to='membership.membershipplan', verbose_name='对应套餐')),
            ],
            options={
                'verbose_name': '卡密兑换码',
                'verbose_name_plural': '卡密兑换码',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='membership__code_7d8892_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('end_at', models.DateTimeField(verbose_name='到期时间')),
                ('remaining_creations', models.IntegerField(default=0, verbose_name='剩余创作次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='membership.membershipplan', verbose_name='所属套餐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户会员',
                'verbose_name_plural': '用户会员',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='membership__user_id_33eeae_idx'), models.Index(fields=['end_at'], name='membership__end_at_15b8d1_idx')],
            },
        ),
    ]
