# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-14 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_rechargepackage_discount_percent'),
        ('skill', '0015_rename_skill_llm_u_created_8a1b0d_idx_skill_llm_u_created_e98b13_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coinledger',
            new_name='billing_coi_user_id_2625da_idx',
            old_name='billing_coi_user_id_6a8fbd_idx',
        ),
        migrations.RenameIndex(
            model_name='coinledger',
            new_name='billing_coi_action__12faea_idx',
            old_name='billing_coi_action__f8e2a1_idx',
        ),
        migrations.AlterField(
            model_name='aifieldpromptconfig',
            name='llm_provider',
            field=models.ForeignKey(blank=True, help_text='留空则使用全局激活的大模型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_field_prompts', to='skill.llmprovider', verbose_name='指定大模型'),
        ),
    ]
