# -*- coding: utf-8 -*-
"""动态配置中心默认种子。

只放适合在线调整的普通业务配置。密钥、数据库、Redis、JWT、CORS、
模型状态枚举等启动期或 schema 级配置禁止放入此处。
"""

DEFAULT_CONFIG_CATEGORIES = [
    {"code": "system", "name": "系统配置", "description": "站点展示与通用参数", "sort_order": 10},
    {"code": "business", "name": "业务配置", "description": "跨业务域的普通配置", "sort_order": 20},
    {"code": "payment", "name": "支付配置", "description": "支付方式与支付开关", "sort_order": 30},
    {"code": "membership", "name": "会员配置", "description": "会员展示与权益辅助配置", "sort_order": 40},
    {"code": "creation", "name": "创作业务配置", "description": "创作流程默认值与阈值", "sort_order": 50},
    {"code": "monitoring", "name": "监控配置", "description": "监控采样与保留策略", "sort_order": 60},
    {"code": "security", "name": "安全配置", "description": "限流等可运营安全参数", "sort_order": 70},
    {"code": "copywriting", "name": "文案配置", "description": "页面文案与运营内容", "sort_order": 80},
]


DEFAULT_SYSTEM_CONFIGS = [
    {
        "category": "system",
        "config_key": "system.site_name",
        "config_name": "站点名称",
        "value_type": "string",
        "value": "ScriptForge 短剧创作平台",
        "default_value": "ScriptForge 短剧创作平台",
        "description": "用于后台快照和前台展示的站点名称",
        "is_public": True,
        "validation_schema": {"min_length": 1, "max_length": 80},
    },
    {
        "category": "system",
        "config_key": "system.support_email",
        "config_name": "客服邮箱",
        "value_type": "string",
        "value": "support@scriptforge.local",
        "default_value": "support@scriptforge.local",
        "description": "默认客服邮箱展示",
        "is_public": True,
        "validation_schema": {"max_length": 120},
    },
    {
        "category": "payment",
        "config_key": "payment.default_method",
        "config_name": "默认支付方式",
        "value_type": "string",
        "value": "mock",
        "default_value": "mock",
        "description": "前端发起支付时的默认方式，生产环境应由后端返回真实可用方式",
        "is_public": True,
        "validation_schema": {"enum": ["mock", "wechat", "alipay"]},
    },
    {
        "category": "creation",
        "config_key": "creation.default_episode_count",
        "config_name": "默认集数",
        "value_type": "int",
        "value": 80,
        "default_value": 80,
        "description": "创作表单默认集数",
        "is_public": True,
        "validation_schema": {"min": 1, "max": 500},
    },
    {
        "category": "creation",
        "config_key": "creation.max_outline_chars",
        "config_name": "大纲最大字数",
        "value_type": "int",
        "value": 8000,
        "default_value": 8000,
        "description": "创作表单大纲/参考资料最大字数提示",
        "is_public": True,
        "validation_schema": {"min": 1000, "max": 50000},
    },
    {
        "category": "creation",
        "config_key": "creation.ai_field_fallback_cost",
        "config_name": "AI 字段生成默认扣费",
        "value_type": "int",
        "value": 10,
        "default_value": 10,
        "description": "AI 字段定价接口不可用时的展示兜底",
        "is_public": True,
        "validation_schema": {"min": 0, "max": 10000},
    },
    {
        "category": "monitoring",
        "config_key": "monitoring.frontend_sample_rate",
        "config_name": "前端监控采样率",
        "value_type": "float",
        "value": 1.0,
        "default_value": 1.0,
        "description": "前端监控上报采样率，范围 0-1",
        "is_public": True,
        "validation_schema": {"min": 0, "max": 1},
    },
    {
        "category": "security",
        "config_key": "security.rate_limit_per_minute",
        "config_name": "默认限流阈值",
        "value_type": "int",
        "value": 120,
        "default_value": 120,
        "description": "普通接口默认每分钟限流阈值，修改需谨慎",
        "is_public": False,
        "validation_schema": {"min": 1, "max": 10000},
    },
    {
        "category": "copywriting",
        "config_key": "home.hero_stats",
        "config_name": "首页核心数据文案",
        "value_type": "array",
        "value": [],
        "default_value": [],
        "description": "首页营销数据展示项，后续可逐步接入",
        "is_public": True,
    },
]
