import type { SettingsFieldDef, SettingsGroupDef, StageDefinition, ModuleCatalogItem } from '@/types/workbench'

/** Derived from workbench/workbench.yaml — contract-driven UI metadata */

export const SETTINGS_GROUPS: SettingsGroupDef[] = [
  { id: 'entry', label_zh: '创作入口', fields: ['entry_type', 'core_idea', 'synopsis', 'external_story', 'adapt_notes', 'reference_dramas'] },
  { id: 'theme', label_zh: '题材与受众', fields: ['genre_matrix', 'flavor_tags', 'preset_theme_code', 'target_platform'] },
  { id: 'scale', label_zh: '篇幅与批次', fields: ['episode_count', 'batch_episode_max', 'outline_mode'] },
  { id: 'production', label_zh: '制作约束', fields: ['production_target_band', 'production_region', 'budget_currency', 'pricing_version', 'budget_excluded_items'] },
  { id: 'quality', label_zh: '质量偏好', fields: ['scoring_preset', 'compliance_check_mode'] },
  { id: 'delivery', label_zh: '交付偏好', fields: ['enable_delivery', 'delivery_items'] },
]

export const SETTINGS_FIELDS: Record<string, SettingsFieldDef> = {
  entry_type: {
    key: 'entry_type',
    type: 'string',
    persist_path: 'entry_type',
    label_zh: '创作入口',
    ui_widget: 'select',
    enum: ['original_track', 'story_adapt'],
    default: 'original_track',
    options: [
      { value: 'original_track', label: '原创通道' },
      { value: 'story_adapt', label: '故事改编通道' },
    ],
  },
  core_idea: {
    key: 'core_idea',
    type: 'string',
    persist_path: 'core_idea',
    label_zh: '核心创意',
    ui_widget: 'textarea',
    visible_when: "entry_type == 'original_track'",
    required_when: "entry_type == 'original_track'",
  },
  synopsis: {
    key: 'synopsis',
    type: 'string',
    persist_path: 'synopsis',
    label_zh: '故事梗概',
    ui_widget: 'textarea',
    visible_when: "entry_type == 'original_track'",
  },
  external_story: {
    key: 'external_story',
    type: 'string',
    persist_path: 'external_story',
    label_zh: '外部故事原文',
    ui_widget: 'textarea',
    required_when: "entry_type == 'story_adapt'",
    visible_when: "entry_type == 'story_adapt'",
  },
  adapt_notes: {
    key: 'adapt_notes',
    type: 'object',
    persist_path: 'adapt_notes',
    label_zh: '改编备注',
    visible_when: "entry_type == 'story_adapt'",
  },
  reference_dramas: {
    key: 'reference_dramas',
    type: 'array',
    persist_path: 'reference_dramas',
    label_zh: '参考剧目',
    ui_widget: 'tags',
  },
  genre_matrix: {
    key: 'genre_matrix',
    type: 'object',
    persist_path: 'genre_matrix',
    label_zh: '四轴题材矩阵',
    ui_widget: 'matrix',
  },
  flavor_tags: {
    key: 'flavor_tags',
    type: 'array',
    persist_path: 'flavor_tags',
    label_zh: '风味标签',
    ui_widget: 'tags',
  },
  preset_theme_code: {
    key: 'preset_theme_code',
    type: 'string',
    persist_path: 'preset_theme_code',
    label_zh: '预设题材模板',
    ui_widget: 'select',
    required: false,
  },
  episode_count: {
    key: 'episode_count',
    type: 'integer',
    persist_path: 'episode_count',
    label_zh: '总集数',
    ui_widget: 'number',
    minimum: 1,
    required: true,
  },
  target_platform: {
    key: 'target_platform',
    type: 'string',
    persist_path: 'target_platform',
    label_zh: '目标平台',
    ui_widget: 'select',
    default: 'generic',
    options: [
      { value: 'generic', label: '通用' },
      { value: 'douyin', label: '抖音' },
      { value: 'kuaishou', label: '快手' },
      { value: 'wechat_miniprogram', label: '微信小程序' },
    ],
  },
  batch_episode_max: {
    key: 'batch_episode_max',
    type: 'integer',
    persist_path: 'creation_preferences.batch_episode_max',
    label_zh: '单批最大集数',
    ui_widget: 'number',
    minimum: 1,
    maximum: 5,
    default: 5,
  },
  outline_mode: {
    key: 'outline_mode',
    type: 'string',
    persist_path: 'creation_preferences.outline_mode',
    label_zh: '大纲模式',
    ui_widget: 'select',
    enum: ['full', 'structure_only'],
    default: 'full',
    options: [
      { value: 'full', label: '完整大纲' },
      { value: 'structure_only', label: '仅结构' },
    ],
  },
  production_target_band: {
    key: 'production_target_band',
    type: 'string',
    persist_path: 'production_context.target_band',
    label_zh: '制作复杂度档位',
    ui_widget: 'select',
    enum: ['lean', 'standard', 'complex'],
    default: 'standard',
    options: [
      { value: 'lean', label: '精简' },
      { value: 'standard', label: '标准' },
      { value: 'complex', label: '复杂' },
    ],
  },
  production_region: {
    key: 'production_region',
    type: 'string',
    persist_path: 'production_context.region',
    label_zh: '制作地区',
    required: false,
  },
  budget_currency: {
    key: 'budget_currency',
    type: 'string',
    persist_path: 'production_context.currency',
    label_zh: '预算币种',
    required: false,
  },
  pricing_version: {
    key: 'pricing_version',
    type: 'string',
    persist_path: 'production_context.pricing_version',
    label_zh: '计价版本',
    required: false,
  },
  budget_excluded_items: {
    key: 'budget_excluded_items',
    type: 'array',
    persist_path: 'production_context.excluded_items',
    label_zh: '预算排除项',
    ui_widget: 'tags',
    required: false,
  },
  scoring_preset: {
    key: 'scoring_preset',
    type: 'string',
    persist_path: 'creation_preferences.scoring_preset',
    label_zh: '评分预设',
    ui_widget: 'select',
    default: 'standard',
    options: [
      { value: 'standard', label: '标准' },
      { value: 'strict', label: '严格' },
      { value: 'relaxed', label: '宽松' },
      { value: 'rhythm_first', label: '节奏优先' },
    ],
  },
  compliance_check_mode: {
    key: 'compliance_check_mode',
    type: 'string',
    persist_path: 'creation_preferences.compliance_check_mode',
    label_zh: '合规检查模式',
    ui_widget: 'select',
    enum: ['standard', 'values-risk', 'full'],
    default: 'standard',
    options: [
      { value: 'standard', label: '标准' },
      { value: 'values-risk', label: '价值观风险' },
      { value: 'full', label: '全量' },
    ],
  },
  enable_delivery: {
    key: 'enable_delivery',
    type: 'boolean',
    persist_path: 'creation_preferences.enable_delivery',
    label_zh: '启用交付包',
    ui_widget: 'switch',
    default: false,
  },
  delivery_items: {
    key: 'delivery_items',
    type: 'array',
    persist_path: 'creation_preferences.delivery_items',
    label_zh: '交付项',
    ui_widget: 'checklist',
    enum_items: ['storyboard', 'visual', 'marketing', 'interactive', 'budget', 'release'],
    default: ['storyboard', 'visual', 'marketing', 'budget'],
    visible_when: 'enable_delivery == true',
    options: [
      { value: 'storyboard', label: '分镜' },
      { value: 'visual', label: '视觉' },
      { value: 'marketing', label: '宣发' },
      { value: 'interactive', label: '互动' },
      { value: 'budget', label: '预算' },
      { value: 'release', label: '上架' },
    ],
  },
}

export const STAGES: StageDefinition[] = [
  {
    id: 'strategy',
    orchestration_phase: 'strategy',
    stage_kind: 'main',
    role: 'drama.topic-director',
    artifact: 'project_brief',
    visible_when: "entry_type == 'original_track'",
    label_zh: '选题定调',
  },
  {
    id: 'blueprint',
    orchestration_phase: 'blueprint',
    stage_kind: 'main',
    role: 'drama.story-bible',
    artifact: 'story_bible',
    approval_required: true,
    label_zh: '剧本蓝图',
  },
  {
    id: 'episode_design',
    orchestration_phase: 'episode_design',
    stage_kind: 'main',
    role: 'drama.episode-designer',
    artifact: 'narrative_plan',
    label_zh: '分集设计',
  },
  {
    id: 'writing',
    orchestration_phase: 'writing',
    stage_kind: 'main',
    role: 'drama.script-writer',
    artifact: 'episode_scripts',
    batch_field: 'episode_range',
    label_zh: '正文创作',
  },
  {
    id: 'quality_score',
    stage_kind: 'quality_loop',
    role: 'drama.script-scorer',
    artifact: 'quality_report',
    parallel_group: 'quality',
    label_zh: '评分',
  },
  {
    id: 'compliance',
    stage_kind: 'quality_loop',
    role: 'drama.compliance-guard',
    artifact: 'compliance_report',
    parallel_group: 'quality',
    label_zh: '合规',
  },
  {
    id: 'revision',
    stage_kind: 'quality_loop',
    role: 'drama.revision-master',
    artifact: 'polished_script',
    conditional: true,
    label_zh: '修复',
  },
  {
    id: 'delivery',
    stage_kind: 'optional',
    role: 'drama.delivery-tool',
    artifact: 'production_package',
    optional: true,
    visible_when: 'enable_delivery == true',
    label_zh: '宣发交付',
  },
]

export const MODULE_CATALOG: ModuleCatalogItem[] = [
  { id: 'concept-development', label_zh: '核心概念形成', domain: 'concept', kind: 'core', lifecycle: 'active', target_roles: ['drama.topic-director'], workbench_visible: true },
  { id: 'market-radar', label_zh: '市场雷达', domain: 'concept', kind: 'core', lifecycle: 'active', target_roles: ['drama.topic-director'], workbench_visible: true },
  { id: 'formula-analysis', label_zh: '商业公式分析', domain: 'concept', kind: 'core', lifecycle: 'active', target_roles: ['drama.topic-director'], workbench_visible: true },
  { id: 'tear-down-6d', label_zh: '六维拉片', domain: 'concept', kind: 'core', lifecycle: 'active', target_roles: ['drama.topic-director'], workbench_visible: true },
  { id: 'character-system', label_zh: '人物系统', domain: 'character', kind: 'core', lifecycle: 'active', target_roles: ['drama.story-bible'], workbench_visible: true },
  { id: 'world-rules', label_zh: '世界规则', domain: 'structure', kind: 'core', lifecycle: 'active', target_roles: ['drama.story-bible'], workbench_visible: true },
  { id: 'series-structure', label_zh: '全剧结构', domain: 'structure', kind: 'core', lifecycle: 'active', target_roles: ['drama.story-bible'], workbench_visible: true },
  { id: 'series-emotion-curve', label_zh: '全剧情绪曲线', domain: 'emotion', kind: 'core', lifecycle: 'active', target_roles: ['drama.story-bible'], workbench_visible: true },
  { id: 'conflict-escalation', label_zh: '冲突升级', domain: 'plotting', kind: 'core', lifecycle: 'active', target_roles: ['drama.story-bible', 'drama.episode-designer'], workbench_visible: true },
  { id: 'reversal-foreshadowing', label_zh: '反转伏笔闭环', domain: 'plotting', kind: 'core', lifecycle: 'active', target_roles: ['drama.story-bible', 'drama.episode-designer'], workbench_visible: true },
  { id: 'adaptation-originality', label_zh: '改编原创化', domain: 'concept', kind: 'core', lifecycle: 'active', target_roles: ['drama.story-bible'], workbench_visible: true, enable_when: "entry_type == 'story_adapt'" },
  { id: 'episode-card', label_zh: '标准分集卡', domain: 'episode', kind: 'core', lifecycle: 'active', target_roles: ['drama.episode-designer'], workbench_visible: true },
  { id: 'episode-emotion-nodes', label_zh: '单集情绪节点', domain: 'emotion', kind: 'core', lifecycle: 'active', target_roles: ['drama.episode-designer'], workbench_visible: true },
  { id: 'hook-system', label_zh: '钩子体系', domain: 'episode', kind: 'core', lifecycle: 'active', target_roles: ['drama.episode-designer'], workbench_visible: true },
  { id: 'payment-checkpoint', label_zh: '付费卡点', domain: 'episode', kind: 'core', lifecycle: 'active', target_roles: ['drama.episode-designer'], workbench_visible: true },
  { id: 'scene-writing', label_zh: '场景写作', domain: 'writing', kind: 'core', lifecycle: 'active', target_roles: ['drama.script-writer'], workbench_visible: true },
  { id: 'dialogue-craft', label_zh: '首稿对白', domain: 'writing', kind: 'core', lifecycle: 'active', target_roles: ['drama.script-writer'], workbench_visible: true },
  { id: 'continuity-snapshot', label_zh: '连续性快照', domain: 'writing', kind: 'core', lifecycle: 'active', target_roles: ['drama.script-writer'], workbench_visible: true },
  { id: 'production-feasibility', label_zh: '制片可拍性', domain: 'production', kind: 'core', lifecycle: 'active', target_roles: ['drama.script-writer'], workbench_visible: true },
  { id: 'continuity-audit', label_zh: '连续性终审', domain: 'quality', kind: 'core', lifecycle: 'active', target_roles: ['drama.script-scorer'], workbench_visible: true },
  { id: 'dialogue-polish', label_zh: '对白精修', domain: 'revision', kind: 'core', lifecycle: 'active', target_roles: ['drama.revision-master'], workbench_visible: true },
  { id: 'format-fix', label_zh: '格式修复', domain: 'revision', kind: 'core', lifecycle: 'active', target_roles: ['drama.revision-master'], workbench_visible: true },
  { id: 'word-count-governance', label_zh: '字数治理', domain: 'revision', kind: 'core', lifecycle: 'active', target_roles: ['drama.revision-master'], workbench_visible: true },
  { id: 'storyboard-9col', label_zh: '九列分镜', domain: 'production', kind: 'extension', lifecycle: 'active', target_roles: ['drama.delivery-tool'], workbench_visible: true, enable_when: "deliverables contains 'storyboard'" },
  { id: 'visual-anchor', label_zh: '视觉锚点', domain: 'marketing', kind: 'extension', lifecycle: 'active', target_roles: ['drama.delivery-tool'], workbench_visible: true, enable_when: "deliverables contains 'visual'" },
  { id: 'marketing-copy', label_zh: '宣发文案', domain: 'marketing', kind: 'extension', lifecycle: 'active', target_roles: ['drama.delivery-tool'], workbench_visible: true, enable_when: "deliverables contains 'marketing'" },
  { id: 'delivery-check', label_zh: '交付门禁', domain: 'delivery', kind: 'extension', lifecycle: 'active', target_roles: ['drama.delivery-tool'], workbench_visible: true },
  { id: 'story-to-game', label_zh: '互动改编', domain: 'derivative', kind: 'extension', lifecycle: 'active', target_roles: ['drama.delivery-tool'], workbench_visible: true, enable_when: "deliverables contains 'interactive'" },
  { id: 'budget-estimator', label_zh: '制作预算分级', domain: 'production', kind: 'extension', lifecycle: 'active', target_roles: ['drama.delivery-tool'], workbench_visible: true, enable_when: "deliverables contains 'budget'" },
  { id: 'platform-ops-checklist', label_zh: '平台上架清单', domain: 'delivery', kind: 'extension', lifecycle: 'active', target_roles: ['drama.delivery-tool'], workbench_visible: true, enable_when: "deliverables contains 'release'" },
]

export const ADMIN_SECTIONS = [
  { id: 'model_routing', label_zh: '模型路由', source: 'foundation/constraints/agent-runtime.yaml' },
  { id: 'script_format', label_zh: '剧本格式', source: 'foundation/constraints/script-format.yaml' },
  { id: 'quality_thresholds', label_zh: '质量阈值', source: 'foundation/constraints/quality-scoring.yaml' },
  { id: 'commercial', label_zh: '商业公式', source: 'foundation/constraints/commercial-formulas.yaml' },
  { id: 'scoring_presets', label_zh: '评分预设', source: 'foundation/constraints/scoring-presets.yaml' },
  { id: 'platform_policies', label_zh: '平台政策', source: 'foundation/constraints/platform-profiles.yaml' },
  { id: 'production_feasibility', label_zh: '制片可行性', source: 'foundation/constraints/production-feasibility.yaml' },
] as const

export const USER_DECISION_OPTIONS = [
  { value: 'accept_current' as const, label: '接受当前批次' },
  { value: 'manual_revision' as const, label: '手动修复' },
  { value: 'abandon_batch' as const, label: '放弃本批' },
]

export const DELIVERY_TAB_ITEMS = [
  { id: 'storyboard', label: '分镜' },
  { id: 'visual', label: '视觉' },
  { id: 'marketing', label: '宣发' },
  { id: 'interactive', label: '互动' },
  { id: 'budget', label: '预算' },
  { id: 'release', label: '上架' },
] as const

export const PC_MIN_WIDTH = 1280
