# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-18 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_default_pack_skill_id_backfill'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nodeexecution',
            name='ne_inst_node_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='nodeexecution',
            name='ne_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='nodeexecution',
            name='ne_inst_attempt_idx',
        ),
        migrations.RemoveIndex(
            model_name='nodeexecution',
            name='ne_inst_started_idx',
        ),
        migrations.RemoveIndex(
            model_name='nodeexecution',
            name='ne_runner_status_idx',
        ),
        migrations.RemoveField(
            model_name='nodeexecutionevent',
            name='execution',
        ),
        migrations.RemoveIndex(
            model_name='workflowinstance',
            name='inst_project_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowinstance',
            name='inst_pack_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowinstance',
            name='inst_heartbeat_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowinstance',
            name='inst_pack_stat_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowinstance',
            name='inst_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowinstance',
            name='inst_trigger_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='fusionpipelinenode',
            name='node_pack_en_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='fusionpipelinenode',
            name='node_pack_skill_idx',
        ),
        migrations.RemoveIndex(
            model_name='fusionpipelinepack',
            name='pack_active_portal_idx',
        ),
        migrations.AlterField(
            model_name='fusionpipelinenode',
            name='condition_expr',
            field=models.TextField(blank=True, default='', help_text="Python 安全表达式，返回 bool。可用变量：ctx（全局上下文）、prev（上一节点输出）、nodes（所有已完成节点输出 dict）。例：ctx.review_score < 70 或 nodes['node_brief']['is_ok']", verbose_name='执行条件表达式'),
        ),
        migrations.AlterField(
            model_name='fusionpipelinenode',
            name='downstream_map',
            field=models.JSONField(blank=True, default=list, help_text="本节点成功后的可选中转目标，支持条件分支。结构:[{target: 'node_b_id', condition_expr: 'ctx.field > 70', weight: 100}]。空列表时由引擎按全局 DAG 选择下一节点。", verbose_name='下游路由映射'),
        ),
        migrations.AlterField(
            model_name='fusionpipelinenode',
            name='runner_type',
            field=models.CharField(blank=True, choices=[('fusion_node', '融合主链节点'), ('parallel_group', '并行节点组（同级并发）'), ('iterate_loop', '迭代循环节点'), ('human_gate', '人工门控节点（分步确认）')], default='', max_length=32, verbose_name='执行器类型'),
        ),
        migrations.AlterField(
            model_name='fusionpipelinenode',
            name='runtime_config',
            field=models.JSONField(blank=True, default=dict, help_text='示例:\n{\n  "timeout_seconds": 600,\n  "retry_policy": {\n    "max_retries": 3,\n    "backoff": "exponential",       // exponential | fixed | linear\n    "base_seconds": 2\n  },\n  "coin_cost_override": null,\n  "allow_skip": true,\n  "is_checkpoint": true,\n  "human_gate_required": false,\n  "max_context_bytes": 2097152,\n  "idempotency_scope": "node"        // node | instance | global\n}', verbose_name='运行时配置'),
        ),
        migrations.AlterField(
            model_name='fusionpipelinenode',
            name='skill_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='用于 SkillBridge 路由。例：creation.brief / fusion.skill.review', max_length=128, verbose_name='技能 ID'),
        ),
        migrations.AlterField(
            model_name='fusionpipelinenode',
            name='upstream_deps',
            field=models.JSONField(blank=True, default=list, help_text="依赖的上游 fusion_node_id 列表，例: ['node-brief', 'node-structure']。引擎将按依赖关系决定调度顺序，替代原有的 chain_order 硬编码依赖", verbose_name='上游依赖'),
        ),
        migrations.AlterField(
            model_name='fusionpipelinepack',
            name='engine_config',
            field=models.JSONField(blank=True, default=dict, help_text='编排引擎全局配置示例:\n{\n  "mode": "async_celery",                 // async_celery | async_thread | sync_debug\n  "timeout_seconds": 3600,                // 工作流整体超时\n  "max_retries": 3,                       // 默认节点重试次数\n  "failure_strategy": "fail_fast",        // fail_fast | continue_on_failure\n  "context_retention_days": 30,           // 上下文保留天数\n  "allow_parallel": true,                 // 是否允许并行组调度\n  "max_parallel_per_group": 5,            // 单并行组最大并发数\n  "heartbeat_interval_seconds": 60        // 心跳频率\n}', verbose_name='引擎配置'),
        ),
        migrations.AlterField(
            model_name='fusionpipelinepack',
            name='parent_version',
            field=models.CharField(blank=True, default='', help_text='记录此版本从哪个版本克隆/升级，支持版本间差异对比', max_length=64, verbose_name='父版本追踪'),
        ),
        migrations.AlterField(
            model_name='fusionpipelinepack',
            name='rollback_to',
            field=models.ForeignKey(blank=True, help_text='标记此包为某次回滚操作的目标版本', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_targets', to='workflow.fusionpipelinepack', verbose_name='回滚目标包'),
        ),
        migrations.RemoveField(
            model_name='nodeexecution',
            name='instance',
        ),
        migrations.DeleteModel(
            name='NodeExecutionEvent',
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='project',
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='rollback_from_instance',
        ),
        migrations.DeleteModel(
            name='NodeExecution',
        ),
        migrations.DeleteModel(
            name='WorkflowInstance',
        ),
    ]
