# -*- coding: utf-8 -*-
"""大模型目录种子数据（仅用于 migration / 空库初始化，运行时读 DB）。"""
from __future__ import annotations

from typing import Any, Dict, List

CATALOG_SEED: List[Dict[str, Any]] = [
    {
        "preset_key": "gpt-4o-mini",
        "name": "GPT-4o mini",
        "vendor": "openai",
        "vendor_label": "OpenAI",
        "base_url": "https://api.openai.com/v1",
        "model_name": "gpt-4o-mini",
        "temperature": 0.7,
        "max_tokens": 8192,
        "context_window_input": 128000,
        "api_key_hint": "OpenAI API Key",
        "api_key_url": "https://platform.openai.com/api-keys",
        "remark": "OpenAI 官方兼容接入",
        "input_price_per_million": "1.0900",
        "output_price_per_million": "4.3600",
        "sort_order": 5,
    },
    {
        "preset_key": "kimi-k2.5",
        "name": "Kimi K2.5",
        "vendor": "moonshot",
        "vendor_label": "Moonshot",
        "base_url": "https://api.moonshot.cn/v1",
        "model_name": "kimi-k2.5",
        "temperature": 0.6,
        "max_tokens": 8192,
        "context_window_input": 256000,
        "supports_multimodal": True,
        "api_key_hint": "Moonshot 开放平台 API Key",
        "api_key_url": "https://platform.moonshot.cn/console/api-keys",
        "remark": "海外可用 api.moonshot.ai/v1",
        "input_price_per_million": "4.3600",
        "output_price_per_million": "21.8100",
        "sort_order": 10,
    },
    {
        "preset_key": "kimi-k2.6",
        "name": "Kimi K2.6",
        "vendor": "moonshot",
        "vendor_label": "Moonshot",
        "base_url": "https://api.moonshot.cn/v1",
        "model_name": "kimi-k2.6",
        "temperature": 0.6,
        "max_tokens": 8192,
        "context_window_input": 256000,
        "supports_multimodal": True,
        "api_key_hint": "Moonshot 开放平台 API Key",
        "api_key_url": "https://platform.moonshot.cn/console/api-keys",
        "remark": "最新旗舰，支持 Agent 与多模态",
        "input_price_per_million": "6.5400",
        "output_price_per_million": "26.9000",
        "sort_order": 11,
    },
    {
        "preset_key": "glm-5",
        "name": "GLM-5（智谱原生）",
        "vendor": "zhipu",
        "vendor_label": "智谱 AI",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "model_name": "glm-5",
        "temperature": 0.7,
        "max_tokens": 8192,
        "context_window_input": 200000,
        "api_key_hint": "智谱开放平台 API Key",
        "api_key_url": "https://open.bigmodel.cn/usercenter/apikeys",
        "remark": "Script 节点推荐；走 open.bigmodel.cn 原生 API，不用火山 ep-xxx",
        "input_price_per_million": "4.0000",
        "output_price_per_million": "16.0000",
        "sort_order": 20,
    },
    {
        "preset_key": "glm-5-turbo",
        "name": "GLM-5-Turbo",
        "vendor": "zhipu",
        "vendor_label": "智谱 AI",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "model_name": "glm-5-turbo",
        "temperature": 1.0,
        "max_tokens": 8192,
        "context_window_input": 204800,
        "api_key_hint": "智谱开放平台 API Key",
        "api_key_url": "https://open.bigmodel.cn/usercenter/apikeys",
        "remark": "GLM-5 高速版",
        "input_price_per_million": "5.0000",
        "output_price_per_million": "22.0000",
        "sort_order": 21,
    },
    {
        "preset_key": "doubao-seed-2.0-pro",
        "name": "Doubao Seed 2.0 Pro（火山）",
        "vendor": "volcengine",
        "vendor_label": "火山方舟",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "model_name": "doubao-seed-2.0-pro",
        "temperature": 0.7,
        "max_tokens": 8192,
        "api_key_hint": "火山方舟 API Key（Coding Plan 或按量付费）",
        "api_key_url": "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
        "remark": "Script 备选；Model ID: doubao-seed-2.0-pro；后台选 Coding Plan Key 类型",
        "force_model_name_sync": True,
        "input_price_per_million": "3.2000",
        "output_price_per_million": "16.0000",
        "sort_order": 30,
    },
    {
        "preset_key": "doubao-seed-2.0-lite",
        "name": "Doubao Seed 2.0 Lite（火山）",
        "vendor": "volcengine",
        "vendor_label": "火山方舟",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "model_name": "doubao-seed-2.0-lite",
        "temperature": 0.7,
        "max_tokens": 8192,
        "api_key_hint": "火山方舟 API Key；按量付费 model 填 ep-xxx（推理接入点 ID）",
        "api_key_url": "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
        "remark": "Polish/Insight；Chat API model=ep-xxx，见火山方舟在线推理接入点",
        "input_price_per_million": "0.6000",
        "output_price_per_million": "3.6000",
        "sort_order": 31,
    },
    {
        "preset_key": "ark-deepseek-v4-flash",
        "name": "DeepSeek V4 Flash（火山）",
        "vendor": "volcengine",
        "vendor_label": "火山方舟",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "model_name": "deepseek-v4-flash",
        "temperature": 0.6,
        "max_tokens": 8192,
        "context_window_input": 1000000,
        "api_key_hint": "火山方舟 API Key；按量付费 model 填 ep-xxx 或配置 VOLCANO_EP_*",
        "api_key_url": "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
        "remark": "World/Character/Outline；Chat API 见 https://www.volcengine.com/docs/82379/1494384",
        "input_price_per_million": "1.0000",
        "output_price_per_million": "2.0000",
        "sort_order": 32,
    },
    {
        "preset_key": "ark-deepseek-v4-pro",
        "name": "DeepSeek V4 Pro（火山）",
        "vendor": "volcengine",
        "vendor_label": "火山方舟",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "model_name": "deepseek-v4-pro",
        "temperature": 0.7,
        "max_tokens": 8192,
        "context_window_input": 1000000,
        "api_key_hint": "火山方舟 API Key；按量付费 model 填 ep-xxx（推理接入点 ID）",
        "api_key_url": "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
        "remark": "Character 等 JSON 节点；model=ep-xxx，或 VOLCANO_EP_DEEPSEEK_V4_PRO",
        "input_price_per_million": "12.0000",
        "output_price_per_million": "24.0000",
        "sort_order": 33,
    },
    {
        "preset_key": "ark-minimax-m2.7",
        "name": "MiniMax M2.7（火山）",
        "vendor": "volcengine",
        "vendor_label": "火山方舟",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "model_name": "MiniMax-M2.7",
        "temperature": 0.7,
        "max_tokens": 8192,
        "context_window_input": 204800,
        "api_key_hint": "火山方舟 API Key（需勾选 Model ID 权限）",
        "api_key_url": "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
        "remark": "Script 备选；Model ID 或 ep-xxx 均可",
        "input_price_per_million": "2.1000",
        "output_price_per_million": "8.4000",
        "sort_order": 34,
    },
    {
        "preset_key": "minimax-m2.7",
        "name": "MiniMax M2.7",
        "vendor": "minimax",
        "vendor_label": "MiniMax",
        "base_url": "https://api.minimax.io/v1",
        "model_name": "MiniMax-M2.7",
        "temperature": 0.7,
        "max_tokens": 8192,
        "context_window_input": 204800,
        "api_key_hint": "MiniMax 开放平台 API Key",
        "api_key_url": "https://platform.minimaxi.com/user-center/basic-information/interface-key",
        "remark": "国内可用 api.minimaxi.com/v1",
        "input_price_per_million": "2.1000",
        "output_price_per_million": "8.4000",
        "sort_order": 40,
    },
    {
        "preset_key": "deepseek-v4-pro",
        "name": "DeepSeek V4 Pro",
        "vendor": "deepseek",
        "vendor_label": "DeepSeek",
        "base_url": "https://api.deepseek.com",
        "model_name": "deepseek-v4-pro",
        "temperature": 0.7,
        "max_tokens": 8192,
        "context_window_input": 1000000,
        "api_key_hint": "DeepSeek 开放平台 API Key",
        "api_key_url": "https://platform.deepseek.com/api_keys",
        "remark": "V4 旗舰，1M 上下文",
        "input_price_per_million": "12.0000",
        "output_price_per_million": "24.0000",
        "sort_order": 50,
    },
    {
        "preset_key": "deepseek-v4-flash",
        "name": "DeepSeek V4 Flash",
        "vendor": "deepseek",
        "vendor_label": "DeepSeek",
        "base_url": "https://api.deepseek.com",
        "model_name": "deepseek-v4-flash",
        "temperature": 0.7,
        "max_tokens": 8192,
        "context_window_input": 1000000,
        "api_key_hint": "DeepSeek 开放平台 API Key",
        "api_key_url": "https://platform.deepseek.com/api_keys",
        "remark": "V4 高速经济版",
        "input_price_per_million": "1.0000",
        "output_price_per_million": "2.0000",
        "sort_order": 51,
    },
]

VENDOR_API_KEY_URLS = {
    "openai": "https://platform.openai.com/api-keys",
    "moonshot": "https://platform.moonshot.cn/console/api-keys",
    "zhipu": "https://open.bigmodel.cn/usercenter/apikeys",
    "volcengine": "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    "minimax": "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    "deepseek": "https://platform.deepseek.com/api_keys",
}
