# Generated by Django 6.0.7 on 2026-07-15 02:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DramaConfigRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(unique=True, verbose_name='版本号')),
                ('overlay', models.JSONField(verbose_name='覆盖内容')),
                ('updated_by', models.CharField(max_length=128, verbose_name='操作人')),
                ('change_reason', models.CharField(max_length=500, verbose_name='变更原因')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drama_config_revision',
                'ordering': ['revision'],
            },
        ),
        migrations.CreateModel(
            name='DramaProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('settings', models.JSONField(default=dict, verbose_name='项目设置')),
                ('settings_revision', models.PositiveIntegerField(default=1, verbose_name='设置版本')),
                ('skills_version', models.CharField(default='5.0.0', max_length=32, verbose_name='技能版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drama_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drama_project',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DramaWorkflowState',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workflow_state', serialize=False, to='drama.dramaproject')),
                ('state', models.JSONField(default=dict, verbose_name='状态快照')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='状态版本')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drama_workflow_state',
            },
        ),
        migrations.CreateModel(
            name='DramaGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('generation', '生成'), ('scoring', '评分'), ('compliance', '合规'), ('external_review', '外部审稿'), ('parallel_judge', '并行评审')], max_length=32, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('queued', '已入队'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('disabled', '已禁用')], default='pending', max_length=16, verbose_name='状态')),
                ('request_payload', models.JSONField(default=dict, verbose_name='请求')),
                ('result_payload', models.JSONField(blank=True, null=True, verbose_name='结果')),
                ('progress_events', models.JSONField(default=list, verbose_name='进度事件')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Celery 任务 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='drama.dramaproject')),
            ],
            options={
                'db_table': 'drama_generation_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DramaCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.CharField(max_length=128, verbose_name='命令 ID')),
                ('event', models.CharField(max_length=64, verbose_name='事件')),
                ('payload', models.JSONField(default=dict, verbose_name='请求体')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('response_snapshot', models.JSONField(blank=True, null=True, verbose_name='响应快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='drama.dramaproject')),
            ],
            options={
                'db_table': 'drama_command',
            },
        ),
        migrations.CreateModel(
            name='DramaAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=128, verbose_name='操作人')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('detail', models.JSONField(default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='drama.dramaproject')),
            ],
            options={
                'db_table': 'drama_audit_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DramaArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_key', models.CharField(db_index=True, max_length=64, verbose_name='产物键')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('schema_version', models.CharField(max_length=64, verbose_name='Schema 版本')),
                ('payload', models.JSONField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_versions', to='drama.dramaproject')),
            ],
            options={
                'db_table': 'drama_artifact_version',
                'ordering': ['artifact_key', '-version'],
            },
        ),
        migrations.AddIndex(
            model_name='dramaproject',
            index=models.Index(fields=['owner', '-updated_at'], name='drama_proje_owner_i_b1d3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='dramagenerationjob',
            index=models.Index(fields=['project', 'status'], name='drama_gener_project_c965f3_idx'),
        ),
        migrations.AddIndex(
            model_name='dramagenerationjob',
            index=models.Index(fields=['celery_task_id'], name='drama_gener_celery__1d7d30_idx'),
        ),
        migrations.AddIndex(
            model_name='dramacommand',
            index=models.Index(fields=['project', 'command_id'], name='drama_comma_project_d34f06_idx'),
        ),
        migrations.AddConstraint(
            model_name='dramacommand',
            constraint=models.UniqueConstraint(fields=('project', 'command_id'), name='uniq_project_command'),
        ),
        migrations.AddIndex(
            model_name='dramaauditevent',
            index=models.Index(fields=['project', '-created_at'], name='drama_audit_project_8c3d59_idx'),
        ),
        migrations.AddIndex(
            model_name='dramaauditevent',
            index=models.Index(fields=['action', '-created_at'], name='drama_audit_action_9fcb29_idx'),
        ),
        migrations.AddIndex(
            model_name='dramaartifactversion',
            index=models.Index(fields=['project', 'artifact_key', '-version'], name='drama_artif_project_705958_idx'),
        ),
        migrations.AddConstraint(
            model_name='dramaartifactversion',
            constraint=models.UniqueConstraint(fields=('project', 'artifact_key', 'version'), name='uniq_artifact_version'),
        ),
    ]
