# Generated by Django 6.0.5 on 2026-06-22 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DramaProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(db_index=True, unique=True, verbose_name='关联项目ID')),
                ('title', models.CharField(max_length=128, verbose_name='剧名')),
                ('genre_code', models.CharField(default='family-revenge', max_length=32, verbose_name='题材代码')),
                ('total_episodes', models.IntegerField(default=30, verbose_name='总集数')),
                ('target_platform', models.CharField(choices=[('douyin', '抖音'), ('kuaishou', '快手'), ('weixin', '微信小程序'), ('all', '通用')], default='douyin', max_length=32, verbose_name='目标平台')),
                ('track_mode', models.CharField(choices=[('fast', '快速通道（8角色）'), ('expert', '专家通道（36角色）')], default='fast', max_length=16, verbose_name='创作模式')),
                ('current_stage', models.CharField(choices=[('strategy', '战略选题'), ('worldbuilding', '世界构建'), ('plot_design', '剧情设计'), ('writing', '剧本创作'), ('review', '评审质控'), ('polish', '修改润色'), ('production', '制作宣发'), ('compliance', '合规审查'), ('delivered', '已交付')], default='strategy', max_length=32, verbose_name='当前阶段')),
                ('completed_roles', models.JSONField(default=list, verbose_name='已完成角色')),
                ('word_count_stats', models.JSONField(default=dict, help_text="每集字数统计：{'ep1': {'total': 1050, 'dialogue': 320, 'scenes': 2}, ...}", verbose_name='字数统计')),
                ('quality_scores', models.JSONField(default=dict, help_text="{'overall': 82, 'format': 88, 'structure': 85, ...}", verbose_name='8维评分')),
                ('delivery_status', models.CharField(choices=[('pending', '待交付'), ('ready', '可交付'), ('delivered', '已交付')], default='pending', max_length=16, verbose_name='交付状态')),
                ('total_tokens_used', models.IntegerField(default=0, verbose_name='累计Token消耗')),
                ('total_cost_cents', models.IntegerField(default=0, verbose_name='累计费用（分）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drama_projects', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
            options={
                'verbose_name': 'Drama Project',
                'verbose_name_plural': 'Drama Project',
                'db_table': 'drama_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DramaRoleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(db_index=True, max_length=64, verbose_name='角色ID')),
                ('agent_name_zh', models.CharField(max_length=64, verbose_name='角色中文名')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=16, verbose_name='状态')),
                ('input_artifacts', models.JSONField(default=dict, verbose_name='输入产物')),
                ('output_artifacts', models.JSONField(default=dict, verbose_name='输出产物')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示词Token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='生成Token')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token')),
                ('cost_cents', models.IntegerField(default=0, verbose_name='费用（分）')),
                ('elapsed_seconds', models.FloatField(blank=True, null=True, verbose_name='耗时（秒）')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('llm_provider', models.CharField(blank=True, default='', max_length=64, verbose_name='LLM Provider')),
                ('llm_model', models.CharField(blank=True, default='', max_length=128, verbose_name='LLM Model')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drama_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_executions', to='drama.dramaproject', verbose_name='剧本项目')),
            ],
            options={
                'verbose_name': '角色执行记录',
                'verbose_name_plural': '角色执行记录',
                'db_table': 'drama_role_execution',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['drama_project', 'agent_id'], name='drama_role__drama_p_e6dc13_idx'), models.Index(fields=['status', '-created_at'], name='drama_role__status_d47c29_idx')],
            },
        ),
    ]
