# Generated by Django 6.0.5 on 2026-06-22 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0001_initial_drama_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DramaEpisodeArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveSmallIntegerField(db_index=True, verbose_name='集号')),
                ('artifact_key', models.CharField(choices=[('episode_script', '单集剧本'), ('review_report', '审稿报告'), ('quality_report', '质量报告'), ('dialogue_notes', '对白优化建议'), ('polish_result', '润色结果')], max_length=32, verbose_name='产物类型')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='版本号')),
                ('content', models.JSONField(default=dict, verbose_name='产物内容')),
                ('diff_summary', models.TextField(blank=True, default='', verbose_name='变更摘要')),
                ('produced_by_agent', models.CharField(blank=True, default='', max_length=64, verbose_name='生成角色')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='质量分')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drama_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_artifacts', to='drama.dramaproject', verbose_name='剧本项目')),
            ],
            options={
                'verbose_name': '分集产物',
                'verbose_name_plural': '分集产物',
                'db_table': 'drama_episode_artifact',
                'ordering': ['episode_number', 'artifact_key', '-version'],
                'indexes': [models.Index(fields=['drama_project', 'episode_number'], name='drama_episo_drama_p_873d62_idx'), models.Index(fields=['drama_project', 'artifact_key'], name='drama_episo_drama_p_63ede3_idx')],
                'unique_together': {('drama_project', 'episode_number', 'artifact_key', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DramaEpisodeQuality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveSmallIntegerField(db_index=True, verbose_name='集号')),
                ('scores', models.JSONField(default=dict, help_text='{"format":85,"structure":80,"character":75,...,"overall":82}', verbose_name='8维评分')),
                ('issues', models.JSONField(default=list, help_text='[{"dimension":"格式规范","severity":"error","desc":"台词使用了引号","suggestion":"改用冒号后接内容"}]', verbose_name='问题清单')),
                ('word_count_result', models.JSONField(default=dict, verbose_name='字数验证')),
                ('summary', models.TextField(blank=True, default='', verbose_name='综合评估意见')),
                ('evaluated_by_agent', models.CharField(default='drama.quality-reporter', max_length=64, verbose_name='评估角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drama_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_qualities', to='drama.dramaproject', verbose_name='剧本项目')),
            ],
            options={
                'verbose_name': '分集质量评估',
                'verbose_name_plural': '分集质量评估',
                'db_table': 'drama_episode_quality',
                'ordering': ['episode_number'],
                'unique_together': {('drama_project', 'episode_number')},
            },
        ),
    ]
