# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-22 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0002_dramaepisodeartifact_dramaepisodequality'),
    ]

    operations = [
        migrations.CreateModel(
            name='DramaGenerationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('abandoned', '已放弃')], default='draft', max_length=16, verbose_name='计划状态')),
                ('batch_size', models.PositiveSmallIntegerField(default=5, help_text='建议5-10集/批，平衡质量和效率', verbose_name='每批集数')),
                ('total_batches', models.PositiveSmallIntegerField(default=0, verbose_name='总批次')),
                ('completed_batches', models.PositiveSmallIntegerField(default=0, verbose_name='已完成批次')),
                ('current_batch', models.PositiveSmallIntegerField(default=1, verbose_name='当前批次')),
                ('quality_gate_enabled', models.BooleanField(default=True, verbose_name='启用质量门槛')),
                ('quality_gate_score', models.FloatField(default=75.0, help_text='低于此分数触发重写，建议70-80', verbose_name='质量门槛分数')),
                ('auto_proceed_on_pass', models.BooleanField(default=False, help_text='True=自动生成下一批，False=每批需手动确认', verbose_name='通过后自动继续')),
                ('token_budget', models.IntegerField(default=0, help_text='0=不限制，非0=超出后暂停', verbose_name='Token预算')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='已用Token')),
                ('last_completed_episode', models.PositiveSmallIntegerField(default=0, help_text='断点续写用：从此集后继续', verbose_name='最后完成集号')),
                ('avg_tokens_per_episode', models.IntegerField(default=0, verbose_name='每集平均Token')),
                ('estimated_total_minutes', models.FloatField(default=0, verbose_name='预估总耗时（分钟）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drama_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_plan', to='drama.dramaproject', verbose_name='剧本项目')),
            ],
            options={
                'verbose_name': '全局生成计划',
                'verbose_name_plural': '全局生成计划',
                'db_table': 'drama_generation_plan',
            },
        ),
        migrations.CreateModel(
            name='DramaEpisodePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveSmallIntegerField(db_index=True, verbose_name='集号')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('queued', '排队中'), ('generating', '生成中'), ('reviewing', '质检中'), ('pass', '质检通过'), ('fail', '质检不通过'), ('rewrite', '重写中'), ('done', '已完成'), ('skipped', '已跳过')], default='pending', max_length=16, verbose_name='状态')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='质量分')),
                ('quality_gate_threshold', models.FloatField(default=75.0, verbose_name='质量门槛')),
                ('quality_gate_passed', models.BooleanField(default=False, verbose_name='质量门槛通过')),
                ('rewrite_count', models.PositiveSmallIntegerField(default=0, verbose_name='重写次数')),
                ('max_rewrites', models.PositiveSmallIntegerField(default=2, verbose_name='最大重写次数')),
                ('batch_number', models.PositiveSmallIntegerField(default=1, help_text='每批5-10集，按批次编排', verbose_name='批次号')),
                ('estimated_tokens', models.IntegerField(default=0, verbose_name='预估Token')),
                ('actual_tokens', models.IntegerField(default=0, verbose_name='实际Token')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drama_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_plans', to='drama.dramaproject', verbose_name='剧本项目')),
            ],
            options={
                'verbose_name': '分集生成计划',
                'verbose_name_plural': '分集生成计划',
                'db_table': 'drama_episode_plan',
                'ordering': ['episode_number'],
                'indexes': [models.Index(fields=['drama_project', 'status'], name='drama_episo_drama_p_c54c3d_idx'), models.Index(fields=['drama_project', 'batch_number'], name='drama_episo_drama_p_f523e2_idx')],
                'unique_together': {('drama_project', 'episode_number')},
            },
        ),
    ]
