# Generated by Cursor Agent on 2026-06-26
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drama", "0005_merge_dramaproject_into_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dramaepisodequality",
            name="evaluated_by_agent",
            field=models.CharField(
                default="drama.script-scorer",
                max_length=64,
                verbose_name="评估角色",
            ),
        ),
        migrations.AlterField(
            model_name="dramaepisodequality",
            name="scores",
            field=models.JSONField(
                default=dict,
                help_text='{"format":85,"structure":80,"character":75,...,"overall":82}',
                verbose_name="10维评分",
            ),
        ),
    ]
