# Generated by Django 6.0.5 on 2026-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drama", "0006_dramallmcalllog"),
    ]

    operations = [
        migrations.AddField(
            model_name="dramallmcalllog",
            name="injection_manifest",
            field=models.JSONField(blank=True, null=True, verbose_name="注入清单"),
        ),
    ]
