# Generated by Django 6.0.7 on 2026-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0009_v6_decision_objects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiodecision',
            options={'ordering': ['status', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='dramagenerationjob',
            new_name='drama_gener_project_ed725d_idx',
            old_name='drama_gener_project_8a4f21_idx',
        ),
        migrations.RenameIndex(
            model_name='dramagenerationjob',
            new_name='drama_gener_owner_i_ec672b_idx',
            old_name='drama_gener_owner_c_91a2bd_idx',
        ),
        migrations.RenameIndex(
            model_name='dramallmcalllog',
            new_name='drama_llm_c_project_29f43f_idx',
            old_name='drama_llm_p_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dramallmcalllog',
            new_name='drama_llm_c_generat_3cfc34_idx',
            old_name='drama_llm_job_seq_idx',
        ),
        migrations.RenameIndex(
            model_name='dramallmcalllog',
            new_name='drama_llm_c_role_2863f6_idx',
            old_name='drama_llm_role_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dramallmcalllog',
            new_name='drama_llm_c_status_7c1ca2_idx',
            old_name='drama_llm_status_created_idx',
        ),
        migrations.AlterField(
            model_name='dramagenerationjob',
            name='base_revision',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='执行基线版本'),
        ),
        migrations.AlterField(
            model_name='dramaprojectruntime',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='运行元数据'),
        ),
        migrations.AlterField(
            model_name='dramaprojectruntime',
            name='revision',
            field=models.PositiveIntegerField(default=0, verbose_name='工作台版本'),
        ),
    ]
