# Generated by Django 6.0.5 on 2026-07-22 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0011_dramascriptdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='V3Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('entry_type', models.CharField(choices=[('original', '原创'), ('adapt', '改编')], max_length=16)),
                ('stage', models.CharField(choices=[('topic', '选题'), ('blueprint', '蓝图'), ('episodes', '分集'), ('writing', '正文'), ('quality', '质检'), ('delivery', '交付')], default='topic', max_length=32)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drama_v3_project',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='dramascriptdraft',
            new_name='drama_scrip_project_714ca7_idx',
            old_name='drama_scrip_project_67a5e3_idx',
        ),
        migrations.AddField(
            model_name='v3project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v3_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
