# Generated by Django 6.0.5 on 2026-07-23 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0012_v3_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='v3project',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='V3CommandRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', '排队'), ('running', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('unsupported', '本阶段未实现')], default='queued', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('request_payload', models.JSONField(default=dict)),
                ('result_payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v3_command_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_runs', to='drama.v3project')),
            ],
            options={
                'db_table': 'drama_v3_command_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='drama_v3_co_owner_i_e1a974_idx'), models.Index(fields=['command_type', 'status'], name='drama_v3_co_command_cc56bd_idx')],
            },
        ),
    ]
