# Generated by Django 6.0.5 on 2026-07-23 02:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0013_v3project_archived_at_v3commandrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3ArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_key', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('candidate', '候选'), ('committed', '已确认'), ('superseded', '已替代')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='drama.v3commandrun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='drama.v3project')),
            ],
            options={
                'db_table': 'drama_v3_artifact_version',
                'constraints': [models.UniqueConstraint(fields=('project', 'artifact_key', 'version'), name='uniq_v3_artifact_version')],
            },
        ),
    ]
