# Generated by Django 6.0.5 on 2026-07-23 02:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0014_v3_artifact_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3ScriptDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_drafts', to='drama.v3project')),
            ],
            options={
                'db_table': 'drama_v3_script_draft',
                'constraints': [models.UniqueConstraint(fields=('project', 'episode_number'), name='uniq_v3_project_episode_script_draft')],
            },
        ),
    ]
