# Generated by Django 6.0.5 on 2026-07-23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0015_v3_script_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3QualityFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('quality', '质量'), ('compliance', '合规')], max_length=16)),
                ('finding_key', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('severity', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('open', '待处理'), ('accepted', '已接受'), ('resolved', '已解决')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_findings', to='drama.v3project')),
                ('report_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drama.v3artifactversion')),
            ],
            options={
                'db_table': 'drama_v3_quality_finding',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('project', 'source', 'finding_key'),
                        name='uniq_v3_finding_project_source_key',
                    ),
                ],
            },
        ),
    ]
