# Generated by Django 6.0.5 on 2026-07-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0016_v3_quality_finding'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3SystemConfigRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(unique=True)),
                ('overlay', models.JSONField(default=dict)),
                ('updated_by', models.CharField(max_length=128)),
                ('change_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drama_v3_system_config_revision',
                'ordering': ['-revision'],
            },
        ),
    ]
