# Generated by Django 6.0.5 on 2026-07-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drama", "0017_v3_system_config_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="V3RoleModelMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_key", models.CharField(max_length=64, unique=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_mappings",
                        to="drama.dramallmprovider",
                    ),
                ),
            ],
            options={
                "db_table": "drama_v3_role_model_mapping",
            },
        ),
    ]
