# Generated by Django 6.0.5 on 2026-07-23 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0018_v3_role_model_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='dramallmcalllog',
            name='v3_command_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_call_logs', to='drama.v3commandrun'),
        ),
        migrations.AddField(
            model_name='dramallmcalllog',
            name='v3_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_call_logs', to='drama.v3project'),
        ),
        migrations.AddIndex(
            model_name='dramallmcalllog',
            index=models.Index(fields=['v3_command_run', '-created_at'], name='drama_llm_c_v3_comm_410dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='dramallmcalllog',
            index=models.Index(fields=['v3_project', '-created_at'], name='drama_llm_c_v3_proj_beea13_idx'),
        ),
    ]
