# Generated by Django 6.0.5 on 2026-07-23 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0019_dramallmcalllog_v3_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='v3rolemodelmapping',
            name='backup_provider_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='V3FailoverAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_key', models.CharField(max_length=64)),
                ('attempt_index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('succeeded', '成功'), ('failed_switchable', '可切换失败'), ('failed_terminal', '终态失败'), ('skipped', '跳过')], max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failover_attempts', to='drama.dramallmcalllog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v3_failover_attempts', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failover_attempts', to='drama.dramallmprovider')),
                ('v3_command_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failover_attempts', to='drama.v3commandrun')),
                ('v3_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failover_attempts', to='drama.v3project')),
            ],
            options={
                'db_table': 'drama_v3_failover_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['v3_command_run', '-created_at'], name='drama_v3_fa_v3_comm_86eb6c_idx')],
            },
        ),
    ]
