# Generated by Django 6.0.5 on 2026-07-23 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0020_v3_failover_attempt_and_backup_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3ModelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('price_in_per_1k', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price_out_per_1k', models.DecimalField(decimal_places=6, max_digits=16)),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_prices', to='drama.dramallmprovider')),
            ],
            options={
                'db_table': 'drama_v3_model_price',
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_name'), name='uniq_v3_model_price_provider_model')],
            },
        ),
    ]
