# Generated by Django 6.0.5 on 2026-07-23 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0021_v3_model_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='V3UsageDailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('command_type', models.CharField(blank=True, max_length=64, null=True)),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_tokens', models.BigIntegerField(default=0)),
                ('completion_tokens', models.BigIntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('unpriced_call_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v3_usage_daily_rollups', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_daily_rollups', to='drama.v3project')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_daily_rollups', to='drama.dramallmprovider')),
            ],
            options={
                'db_table': 'drama_v3_usage_daily_rollup',
                'constraints': [models.UniqueConstraint(fields=('date', 'owner', 'project', 'command_type', 'model_name', 'provider'), name='uniq_v3_usage_daily_rollup_dims', nulls_distinct=False)],
            },
        ),
    ]
