# Generated by Django 6.0.5 on 2026-07-23 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0022_v3_usage_daily_rollup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='v3project',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='V3ProjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('theme_code', models.CharField(max_length=64)),
                ('label_zh', models.CharField(max_length=200)),
                ('dims', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v3_project_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drama_v3_project_template',
                'ordering': ['-updated_at'],
            },
        ),
    ]
