# Generated by Django 6.0.5 on 2026-07-23 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0023_v3_project_template_and_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3LlmProviderKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, verbose_name='标签')),
                ('api_key_encrypted', models.TextField(blank=True, default='', verbose_name='加密 API Key')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_keys', to='drama.dramallmprovider')),
            ],
            options={
                'verbose_name': 'LLM 附加密钥',
                'verbose_name_plural': 'LLM 附加密钥',
                'db_table': 'drama_v3_llm_provider_key',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['provider', 'sort_order'], name='drama_v3_ll_provide_cec0e6_idx')],
            },
        ),
    ]
